// Generated by OrchestKit Claude Plugin
// Created: 2026-06-23

// src/db/postgres.test.ts
import assert from "node:assert/strict";
import test from "node:test";

test("getPgDb throws a clear error when no postgres url is configured", async () => {
  const prev = process.env.VIRLY_POSTGRES_URL;
  delete process.env.VIRLY_POSTGRES_URL;
  const mod = await import(`./postgres.js?ts=${Date.now()}`);
  assert.throws(() => mod.getPgDb(), /VIRLY_POSTGRES_URL/);
  if (prev) process.env.VIRLY_POSTGRES_URL = prev;
});
