// Generated by OrchestKit Claude Plugin
// Created: 2026-06-22

import type { AiAuditLogRepository } from "../types.js";
import { stubRepository } from "./stub.js";

export const mongoAiAuditLogRepository = stubRepository<AiAuditLogRepository>("mongoAiAuditLogRepository");
