// Generated by OrchestKit Claude Plugin
// Created: 2026-06-22

import type { AiConversationRepository } from "../types.js";
import { stubRepository } from "./stub.js";

export const mongoAiConversationRepository = stubRepository<AiConversationRepository>("mongoAiConversationRepository");
