// Generated by OrchestKit Claude Plugin
// Created: 2026-06-22

import type { AiPendingTransferRepository } from "../types.js";
import { stubRepository } from "./stub.js";

export const mongoAiPendingTransferRepository = stubRepository<AiPendingTransferRepository>("mongoAiPendingTransferRepository");
