// Generated by OrchestKit Claude Plugin
// Created: 2026-06-22

import type { ExchangeRateRepository } from "../types.js";
import { stubRepository } from "./stub.js";

export const mongoExchangeRateRepository = stubRepository<ExchangeRateRepository>("mongoExchangeRateRepository");
