// Generated by OrchestKit Claude Plugin
// Created: 2026-06-22

// src/repositories/mongo/index.ts
import type { Repositories } from "../types.js";
import { runInTransaction } from "./transaction.js";
import { mongoUserRepository } from "./user.repository.js";
import { mongoTransactionRepository } from "./transaction.repository.js";
import { mongoPersonalDetailsRepository } from "./personalDetails.repository.js";
import { mongoExchangeRateRepository } from "./exchangeRate.repository.js";
import { mongoAiConversationRepository } from "./aiConversation.repository.js";
import { mongoAiPendingTransferRepository } from "./aiPendingTransfer.repository.js";
import { mongoAiAuditLogRepository } from "./aiAuditLog.repository.js";
import { mongoVideoSessionRepository } from "./videoSession.repository.js";
import { mongoVideoAuditLogRepository } from "./videoAuditLog.repository.js";

export function createMongoRepositories(): Repositories {
  return {
    users: mongoUserRepository,
    transactions: mongoTransactionRepository,
    personalDetails: mongoPersonalDetailsRepository,
    exchangeRates: mongoExchangeRateRepository,
    aiConversations: mongoAiConversationRepository,
    aiPendingTransfers: mongoAiPendingTransferRepository,
    aiAuditLogs: mongoAiAuditLogRepository,
    videoSessions: mongoVideoSessionRepository,
    videoAuditLogs: mongoVideoAuditLogRepository,
    runInTransaction,
  };
}
