// Generated by OrchestKit Claude Plugin
// Created: 2026-06-23

// src/repositories/mongo/personalDetails.repository.test.ts
import assert from "node:assert/strict";
import test from "node:test";
import { PersonalDetails } from "../../models/PersonalDetails.js";
import { mongoPersonalDetailsRepository } from "./personalDetails.repository.js";

function patch<T extends object, K extends keyof T>(o: T, k: K, v: T[K], t: test.TestContext) {
  const orig = o[k]; o[k] = v; t.after(() => { o[k] = orig; });
}

const USER_OID = "507f1f77bcf86cd799439011";
const PD_OID   = "507f191e810c19729de860ea";

const leanPd = {
  _id: PD_OID,
  userId: USER_OID,
  status: "not_provided",
  firstName: null,
  lastName: null,
  dateOfBirth: null,
  address: {},
  lastSkippedAt: null,
  createdAt: new Date("2026-01-01T00:00:00.000Z"),
  updatedAt: new Date("2026-01-01T00:00:00.000Z")
};

// ---------------------------------------------------------------------------
// findByUserId
// ---------------------------------------------------------------------------

test("findByUserId: maps lean doc to PersonalDetailsRecord with string id", async (t) => {
  const fakeChain = { session: () => fakeChain, lean: async () => leanPd };
  patch(
    PersonalDetails,
    "findOne",
    ((_filter: unknown) => fakeChain) as unknown as typeof PersonalDetails.findOne,
    t
  );

  const rec = await mongoPersonalDetailsRepository.findByUserId(USER_OID);

  assert.ok(rec);
  assert.equal(rec.id, PD_OID);
  assert.equal((rec as Record<string, unknown>)._id, undefined, "must not expose _id");
  assert.equal(rec.userId, USER_OID);
  assert.equal(rec.status, "not_provided");
});

test("findByUserId: returns null when not found", async (t) => {
  const fakeChain = { session: () => fakeChain, lean: async () => null };
  patch(
    PersonalDetails,
    "findOne",
    ((_filter: unknown) => fakeChain) as unknown as typeof PersonalDetails.findOne,
    t
  );

  const rec = await mongoPersonalDetailsRepository.findByUserId(USER_OID);
  assert.equal(rec, null);
});

test("findByUserId: queries by userId field", async (t) => {
  let capturedFilter: unknown;
  const fakeChain = {
    session: () => fakeChain,
    lean: async () => null
  };
  patch(
    PersonalDetails,
    "findOne",
    ((filter: unknown) => { capturedFilter = filter; return fakeChain; }) as unknown as typeof PersonalDetails.findOne,
    t
  );

  await mongoPersonalDetailsRepository.findByUserId(USER_OID);
  assert.deepEqual(capturedFilter, { userId: USER_OID });
});

// ---------------------------------------------------------------------------
// ensureForUser
// ---------------------------------------------------------------------------

test("ensureForUser: calls findOneAndUpdate with upsert and returns record", async (t) => {
  let capturedFilter: unknown;
  let capturedUpdate: unknown;
  let capturedOpts: unknown;

  patch(
    PersonalDetails,
    "findOneAndUpdate",
    (async (filter: unknown, update: unknown, opts: unknown) => {
      capturedFilter = filter;
      capturedUpdate = update;
      capturedOpts = opts;
      return { ...leanPd, toObject: () => leanPd };
    }) as unknown as typeof PersonalDetails.findOneAndUpdate,
    t
  );

  const rec = await mongoPersonalDetailsRepository.ensureForUser(USER_OID);

  assert.ok(rec);
  assert.equal(rec.id, PD_OID);
  assert.equal((rec as Record<string, unknown>)._id, undefined);
  assert.equal(rec.userId, USER_OID);
  assert.deepEqual(capturedFilter, { userId: USER_OID });
  assert.ok(
    (capturedOpts as Record<string, unknown>).upsert === true,
    "must use upsert: true"
  );
  assert.ok(
    (capturedOpts as Record<string, unknown>).new === true,
    "must use new: true to return updated doc"
  );
  // Must seed userId on insert
  const setOnInsert = (capturedUpdate as { $setOnInsert?: Record<string, unknown> }).$setOnInsert;
  assert.ok(setOnInsert, "$setOnInsert must be present");
  assert.equal(setOnInsert.userId, USER_OID);
});

test("ensureForUser: returns a record without _id when existing doc found", async (t) => {
  patch(
    PersonalDetails,
    "findOneAndUpdate",
    (async () => ({ ...leanPd, toObject: () => leanPd })) as unknown as typeof PersonalDetails.findOneAndUpdate,
    t
  );

  const rec = await mongoPersonalDetailsRepository.ensureForUser(USER_OID);
  assert.equal(rec.id, PD_OID);
  assert.equal((rec as Record<string, unknown>)._id, undefined);
});

// ---------------------------------------------------------------------------
// update
// ---------------------------------------------------------------------------

test("update: calls findOneAndUpdate with $set patch and returns updated record", async (t) => {
  let capturedFilter: unknown;
  let capturedUpdate: unknown;
  let capturedOpts: unknown;

  const updatedLean = {
    ...leanPd,
    status: "provided",
    firstName: "Alice",
    lastName: "Smith",
    dateOfBirth: new Date("1990-05-15T00:00:00.000Z")
  };

  patch(
    PersonalDetails,
    "findOneAndUpdate",
    (async (filter: unknown, update: unknown, opts: unknown) => {
      capturedFilter = filter;
      capturedUpdate = update;
      capturedOpts = opts;
      return { ...updatedLean, toObject: () => updatedLean };
    }) as unknown as typeof PersonalDetails.findOneAndUpdate,
    t
  );

  const rec = await mongoPersonalDetailsRepository.update(USER_OID, {
    status: "provided",
    firstName: "Alice",
    lastName: "Smith",
    dateOfBirth: new Date("1990-05-15T00:00:00.000Z")
  });

  assert.ok(rec);
  assert.equal(rec.id, PD_OID);
  assert.equal((rec as Record<string, unknown>)._id, undefined);
  assert.equal(rec.status, "provided");
  assert.equal(rec.firstName, "Alice");
  assert.deepEqual(capturedFilter, { userId: USER_OID });
  assert.ok((capturedUpdate as Record<string, unknown>).$set, "update must use $set");
  assert.ok(
    (capturedOpts as Record<string, unknown>).new === true,
    "must use new: true"
  );
});

test("update: spreads patch fields into $set (address stays a plain object)", async (t) => {
  let capturedUpdate: unknown;

  const updatedLean = {
    ...leanPd,
    address: { country: "US", city: "NY", street: "5th Ave", postalCode: "10001", stateRegion: null, addressLine2: null }
  };

  patch(
    PersonalDetails,
    "findOneAndUpdate",
    (async (_f: unknown, update: unknown) => {
      capturedUpdate = update;
      return { ...updatedLean, toObject: () => updatedLean };
    }) as unknown as typeof PersonalDetails.findOneAndUpdate,
    t
  );

  await mongoPersonalDetailsRepository.update(USER_OID, {
    address: { country: "US", city: "NY", street: "5th Ave", postalCode: "10001", stateRegion: null, addressLine2: null }
  });

  const setClause = (capturedUpdate as { $set?: Record<string, unknown> }).$set ?? {};
  assert.deepEqual(setClause.address, {
    country: "US", city: "NY", street: "5th Ave", postalCode: "10001", stateRegion: null, addressLine2: null
  });
});

test("update: passes session when tx context is provided", async (t) => {
  let capturedOpts: unknown;
  const fakeSession = { id: "fake-session" };

  patch(
    PersonalDetails,
    "findOneAndUpdate",
    (async (_f: unknown, _u: unknown, opts: unknown) => {
      capturedOpts = opts;
      return { ...leanPd, toObject: () => leanPd };
    }) as unknown as typeof PersonalDetails.findOneAndUpdate,
    t
  );

  await mongoPersonalDetailsRepository.update(USER_OID, { status: "provided" }, fakeSession);
  assert.equal((capturedOpts as Record<string, unknown>).session, fakeSession);
});

test("update: returns null when no doc exists for the user", async (t) => {
  patch(
    PersonalDetails,
    "findOneAndUpdate",
    (async () => null) as unknown as typeof PersonalDetails.findOneAndUpdate,
    t
  );

  const rec = await mongoPersonalDetailsRepository.update(USER_OID, { status: "provided" });
  assert.equal(rec, null);
});
