// Generated by OrchestKit Claude Plugin
// Created: 2026-06-22

import type { PersonalDetailsRepository } from "../types.js";
import { stubRepository } from "./stub.js";

export const mongoPersonalDetailsRepository = stubRepository<PersonalDetailsRepository>("mongoPersonalDetailsRepository");
