// Generated by OrchestKit Claude Plugin
// Created: 2026-06-22

// src/repositories/mongo/transaction.ts
import mongoose, { type ClientSession } from "mongoose";
import type { TxContext } from "../types.js";

/** Narrow an opaque TxContext to a Mongoose session (or undefined). */
export function asSession(tx?: TxContext): ClientSession | undefined {
  return tx as ClientSession | undefined;
}

export async function runInTransaction<T>(fn: (tx: TxContext) => Promise<T>): Promise<T> {
  const session = await mongoose.startSession();
  try {
    let result: T | undefined;
    let ran = false;
    await session.withTransaction(async () => {
      result = await fn(session);
      ran = true;
    });
    if (!ran) throw new Error("Transaction body did not run.");
    return result as T;
  } finally {
    await session.endSession();
  }
}
