// Generated by OrchestKit Claude Plugin
// Created: 2026-06-22

// src/repositories/mongo/transaction.repository.test.ts
import assert from "node:assert/strict";
import test from "node:test";
import { Types } from "mongoose";
import { Transaction } from "../../models/Transaction.js";
import { mongoTransactionRepository } from "./transaction.repository.js";

function patch<T extends object, K extends keyof T>(o: T, k: K, v: T[K], t: test.TestContext) {
  const orig = o[k]; o[k] = v; t.after(() => { o[k] = orig; });
}

const OWNER_OID = "507f1f77bcf86cd799439011";

const leanTx = {
  _id: "60d5ec49f1b2c8a1f8e4e1b1",
  ownerId: OWNER_OID,
  counterpartyEmail: "bob@example.com",
  amount: 100,
  type: "debit",
  directionLabel: "Sent",
  reason: "lunch",
  enteredCurrency: undefined,
  enteredAmount: undefined,
  exchangeRateUsed: undefined,
  exchangeRateFetchedAt: undefined,
  createdAt: new Date("2026-06-01T12:00:00.000Z"),
  updatedAt: new Date("2026-06-01T12:00:00.000Z")
};

// ---------------------------------------------------------------------------
// createMany
// ---------------------------------------------------------------------------

test("createMany: calls Transaction.create with session and returns records", async (t) => {
  let capturedDocs: unknown;
  let capturedOpts: unknown;
  patch(
    Transaction,
    "create",
    (async (docs: unknown, opts: unknown) => {
      capturedDocs = docs;
      capturedOpts = opts;
      return [{ ...leanTx, toObject: () => leanTx }];
    }) as unknown as typeof Transaction.create,
    t
  );

  const input = [{
    ownerId: OWNER_OID,
    counterpartyEmail: "bob@example.com",
    amount: 100,
    type: "debit" as const,
    directionLabel: "Sent",
    reason: "lunch"
  }];
  const records = await mongoTransactionRepository.createMany(input);

  assert.equal(records.length, 1);
  assert.equal(records[0].id, leanTx._id);
  assert.equal((records[0] as Record<string, unknown>)._id, undefined);
  assert.equal(records[0].ownerId, OWNER_OID);
  assert.ok(Array.isArray(capturedDocs));
  assert.deepEqual((capturedOpts as Record<string, unknown>).ordered, true);
});

// ---------------------------------------------------------------------------
// listForOwner
// ---------------------------------------------------------------------------

test("listForOwner: returns TransactionRecords with string id", async (t) => {
  const fakeChain = {
    sort: () => fakeChain,
    skip: () => fakeChain,
    limit: () => fakeChain,
    lean: async () => [leanTx]
  };
  patch(
    Transaction,
    "find",
    ((_filter: unknown) => fakeChain) as unknown as typeof Transaction.find,
    t
  );
  patch(
    Transaction,
    "countDocuments",
    (async (_filter: unknown) => 1) as unknown as typeof Transaction.countDocuments,
    t
  );

  const { transactions, total } = await mongoTransactionRepository.listForOwner({
    ownerId: OWNER_OID,
    page: 1,
    limit: 10
  });

  assert.equal(total, 1);
  assert.equal(transactions.length, 1);
  assert.equal(transactions[0].id, leanTx._id);
  assert.equal((transactions[0] as Record<string, unknown>)._id, undefined);
});

test("listForOwner: skip is (page-1)*limit", async (t) => {
  let capturedSkip = -1;
  let capturedLimit = -1;
  const fakeChain = {
    sort: () => fakeChain,
    skip: (n: number) => { capturedSkip = n; return fakeChain; },
    limit: (n: number) => { capturedLimit = n; return fakeChain; },
    lean: async () => []
  };
  patch(Transaction, "find", ((_f: unknown) => fakeChain) as unknown as typeof Transaction.find, t);
  patch(Transaction, "countDocuments", (async () => 0) as unknown as typeof Transaction.countDocuments, t);

  await mongoTransactionRepository.listForOwner({ ownerId: OWNER_OID, page: 3, limit: 5 });
  assert.equal(capturedSkip, 10);
  assert.equal(capturedLimit, 5);
});

// ---------------------------------------------------------------------------
// recentWithCounterparty
// ---------------------------------------------------------------------------

test("recentWithCounterparty: returns TransactionRecords sorted desc", async (t) => {
  let capturedFilter: unknown;
  let capturedLimit = -1;
  let capturedSort: unknown;
  const fakeChain = {
    sort: (s: unknown) => { capturedSort = s; return fakeChain; },
    limit: (n: number) => { capturedLimit = n; return fakeChain; },
    lean: async () => [leanTx]
  };
  patch(
    Transaction,
    "find",
    ((filter: unknown) => { capturedFilter = filter; return fakeChain; }) as unknown as typeof Transaction.find,
    t
  );

  const records = await mongoTransactionRepository.recentWithCounterparty({
    ownerId: OWNER_OID,
    counterpartyEmail: "bob@example.com",
    limit: 5
  });

  assert.equal(records.length, 1);
  assert.equal(records[0].id, leanTx._id);
  assert.deepEqual(capturedFilter, { ownerId: OWNER_OID, counterpartyEmail: "bob@example.com" });
  assert.deepEqual(capturedSort, { createdAt: -1 });
  assert.equal(capturedLimit, 5);
});

// ---------------------------------------------------------------------------
// getRelationshipStats
// ---------------------------------------------------------------------------

test("getRelationshipStats: $match uses Types.ObjectId for ownerId", async (t) => {
  let capturedPipeline: unknown[] = [];
  patch(
    Transaction,
    "aggregate",
    (async (pipeline: unknown[]) => { capturedPipeline = pipeline; return []; }) as unknown as typeof Transaction.aggregate,
    t
  );

  await mongoTransactionRepository.getRelationshipStats({
    ownerId: OWNER_OID,
    counterpartyEmail: "bob@example.com"
  });

  const match = (capturedPipeline[0] as { $match: Record<string, unknown> }).$match;
  // The ObjectId cast must live in the repo, not in the consumer
  assert.ok(match.ownerId instanceof Types.ObjectId, "ownerId must be a Types.ObjectId");
  assert.equal(String(match.ownerId), OWNER_OID);
  assert.equal(match.counterpartyEmail, "bob@example.com");
});

test("getRelationshipStats: returns correct fields from aggregate result", async (t) => {
  patch(
    Transaction,
    "aggregate",
    (async () => [{
      totalSent: 500,
      totalReceived: 200.5,
      transactionCount: 7,
      lastTransactionAt: new Date("2026-06-10T08:00:00.000Z")
    }]) as unknown as typeof Transaction.aggregate,
    t
  );

  const result = await mongoTransactionRepository.getRelationshipStats({
    ownerId: OWNER_OID,
    counterpartyEmail: "bob@example.com"
  });

  assert.equal(result.totalSent, 500);
  assert.equal(result.totalReceived, 200.5);
  assert.equal(result.transactionCount, 7);
  assert.deepEqual(result.lastTransactionAt, new Date("2026-06-10T08:00:00.000Z"));
});

test("getRelationshipStats: returns zero-defaults when aggregate is empty", async (t) => {
  patch(Transaction, "aggregate", (async () => []) as unknown as typeof Transaction.aggregate, t);

  const result = await mongoTransactionRepository.getRelationshipStats({
    ownerId: OWNER_OID,
    counterpartyEmail: "bob@example.com"
  });

  assert.equal(result.totalSent, 0);
  assert.equal(result.totalReceived, 0);
  assert.equal(result.transactionCount, 0);
  assert.equal(result.lastTransactionAt, null);
});

// ---------------------------------------------------------------------------
// getDirectionalTotals
// ---------------------------------------------------------------------------

test("getDirectionalTotals: $match uses Types.ObjectId for ownerId", async (t) => {
  let capturedPipeline: unknown[] = [];
  patch(
    Transaction,
    "aggregate",
    (async (pipeline: unknown[]) => { capturedPipeline = pipeline; return []; }) as unknown as typeof Transaction.aggregate,
    t
  );

  await mongoTransactionRepository.getDirectionalTotals({
    ownerId: OWNER_OID,
    counterpartyEmail: "bob@example.com"
  });

  const match = (capturedPipeline[0] as { $match: Record<string, unknown> }).$match;
  assert.ok(match.ownerId instanceof Types.ObjectId, "ownerId must be a Types.ObjectId");
  assert.equal(String(match.ownerId), OWNER_OID);
});

test("getDirectionalTotals: returns credit/debit totals and counts", async (t) => {
  patch(
    Transaction,
    "aggregate",
    (async () => [
      { _id: "credit", total: 300, count: 3 },
      { _id: "debit", total: 150, count: 2 }
    ]) as unknown as typeof Transaction.aggregate,
    t
  );

  const result = await mongoTransactionRepository.getDirectionalTotals({
    ownerId: OWNER_OID,
    counterpartyEmail: "bob@example.com"
  });

  assert.equal(result.creditTotal, 300);
  assert.equal(result.creditCount, 3);
  assert.equal(result.debitTotal, 150);
  assert.equal(result.debitCount, 2);
});

test("getDirectionalTotals: returns zeros when aggregate is empty", async (t) => {
  patch(Transaction, "aggregate", (async () => []) as unknown as typeof Transaction.aggregate, t);

  const result = await mongoTransactionRepository.getDirectionalTotals({
    ownerId: OWNER_OID,
    counterpartyEmail: "bob@example.com"
  });

  assert.equal(result.creditTotal, 0);
  assert.equal(result.creditCount, 0);
  assert.equal(result.debitTotal, 0);
  assert.equal(result.debitCount, 0);
});

// ---------------------------------------------------------------------------
// sumSameDayDebits
// ---------------------------------------------------------------------------

test("sumSameDayDebits: returns sum of debit amounts in day window", async (t) => {
  const dayStart = new Date("2026-06-22T00:00:00.000Z");
  const dayEnd = new Date("2026-06-23T00:00:00.000Z");

  let capturedFilter: unknown;
  const fakeChain = {
    select: () => fakeChain,
    session: () => fakeChain,
    lean: async () => [{ amount: 100 }, { amount: 50.5 }]
  };
  patch(
    Transaction,
    "find",
    ((filter: unknown) => { capturedFilter = filter; return fakeChain; }) as unknown as typeof Transaction.find,
    t
  );

  const result = await mongoTransactionRepository.sumSameDayDebits({
    ownerId: OWNER_OID,
    dayStart,
    dayEnd
  });

  assert.equal(result, 150.5);
  const filter = capturedFilter as Record<string, unknown>;
  assert.equal(filter.ownerId, OWNER_OID);
  assert.equal(filter.type, "debit");
});

test("sumSameDayDebits: returns 0 when no debits found", async (t) => {
  const fakeChain = {
    select: () => fakeChain,
    session: () => fakeChain,
    lean: async () => []
  };
  patch(Transaction, "find", ((_f: unknown) => fakeChain) as unknown as typeof Transaction.find, t);

  const result = await mongoTransactionRepository.sumSameDayDebits({
    ownerId: OWNER_OID,
    dayStart: new Date("2026-06-22T00:00:00.000Z"),
    dayEnd: new Date("2026-06-23T00:00:00.000Z")
  });

  assert.equal(result, 0);
});

// ---------------------------------------------------------------------------
// getDailyDebitUsage
// ---------------------------------------------------------------------------

test("getDailyDebitUsage: returns sum and count of debits in window", async (t) => {
  let capturedFilter: unknown;
  const fakeChain = {
    select: () => fakeChain,
    session: () => fakeChain,
    lean: async () => [{ amount: 100 }, { amount: 50.5 }, { amount: 9.5 }]
  };
  patch(
    Transaction,
    "find",
    ((filter: unknown) => { capturedFilter = filter; return fakeChain; }) as unknown as typeof Transaction.find,
    t
  );

  const result = await mongoTransactionRepository.getDailyDebitUsage({
    ownerId: OWNER_OID,
    dayStart: new Date("2026-06-22T00:00:00.000Z"),
    dayEnd: new Date("2026-06-23T00:00:00.000Z")
  });

  assert.equal(result.total, 160);
  assert.equal(result.count, 3);
  const filter = capturedFilter as Record<string, unknown>;
  assert.equal(filter.ownerId, OWNER_OID);
  assert.equal(filter.type, "debit");
});

test("getDailyDebitUsage: returns zeros when no debits found", async (t) => {
  const fakeChain = {
    select: () => fakeChain,
    session: () => fakeChain,
    lean: async () => []
  };
  patch(Transaction, "find", ((_f: unknown) => fakeChain) as unknown as typeof Transaction.find, t);

  const result = await mongoTransactionRepository.getDailyDebitUsage({
    ownerId: OWNER_OID,
    dayStart: new Date("2026-06-22T00:00:00.000Z"),
    dayEnd: new Date("2026-06-23T00:00:00.000Z")
  });

  assert.equal(result.total, 0);
  assert.equal(result.count, 0);
});

// ---------------------------------------------------------------------------
// findByIdForOwner
// ---------------------------------------------------------------------------

test("findByIdForOwner: returns a record scoped by _id and ownerId", async (t) => {
  let capturedFilter: unknown;
  const fakeChain = {
    session: () => fakeChain,
    lean: async () => leanTx
  };
  patch(
    Transaction,
    "findOne",
    ((filter: unknown) => { capturedFilter = filter; return fakeChain; }) as unknown as typeof Transaction.findOne,
    t
  );

  const record = await mongoTransactionRepository.findByIdForOwner(
    "60d5ec49f1b2c8a1f8e4e1b1",
    OWNER_OID
  );

  assert.ok(record);
  assert.equal(record?.id, leanTx._id);
  assert.equal((record as Record<string, unknown>)._id, undefined);
  assert.deepEqual(capturedFilter, { _id: "60d5ec49f1b2c8a1f8e4e1b1", ownerId: OWNER_OID });
});

test("findByIdForOwner: returns null for a malformed (non-ObjectId) id without querying", async (t) => {
  let queried = false;
  patch(
    Transaction,
    "findOne",
    ((_filter: unknown) => { queried = true; return { lean: async () => null }; }) as unknown as typeof Transaction.findOne,
    t
  );

  const record = await mongoTransactionRepository.findByIdForOwner("not-an-objectid", OWNER_OID);

  assert.equal(record, null);
  assert.equal(queried, false);
});

test("findByIdForOwner: returns null when no document matches", async (t) => {
  const fakeChain = { session: () => fakeChain, lean: async () => null };
  patch(
    Transaction,
    "findOne",
    ((_filter: unknown) => fakeChain) as unknown as typeof Transaction.findOne,
    t
  );

  const record = await mongoTransactionRepository.findByIdForOwner(
    "60d5ec49f1b2c8a1f8e4e1b1",
    OWNER_OID
  );

  assert.equal(record, null);
});

// ---------------------------------------------------------------------------
// listForOwnerFiltered
// ---------------------------------------------------------------------------

test("listForOwnerFiltered: builds filter from plain criteria and maps records", async (t) => {
  let capturedFilter: Record<string, unknown> = {};
  let capturedSort: unknown;
  let capturedLimit = -1;
  const fakeChain = {
    sort: (s: unknown) => { capturedSort = s; return fakeChain; },
    limit: (n: number) => { capturedLimit = n; return fakeChain; },
    lean: async () => [leanTx]
  };
  patch(
    Transaction,
    "find",
    ((filter: Record<string, unknown>) => { capturedFilter = filter; return fakeChain; }) as unknown as typeof Transaction.find,
    t
  );

  const records = await mongoTransactionRepository.listForOwnerFiltered({
    ownerId: OWNER_OID,
    type: "debit",
    counterpartyEmail: "bob@example.com",
    dateFrom: new Date("2026-06-01T00:00:00.000Z"),
    dateTo: new Date("2026-06-30T00:00:00.000Z"),
    minAmount: 10,
    maxAmount: 500,
    reasonContains: "lunch",
    sort: "amount_desc",
    limit: 25
  });

  assert.equal(records.length, 1);
  assert.equal(records[0].id, leanTx._id);
  assert.equal(capturedFilter.ownerId, OWNER_OID);
  assert.equal(capturedFilter.type, "debit");
  assert.equal(capturedFilter.counterpartyEmail, "bob@example.com");
  assert.deepEqual(capturedFilter.amount, { $gte: 10, $lte: 500 });
  assert.ok(capturedFilter.createdAt);
  assert.ok(capturedFilter.reason instanceof RegExp);
  assert.deepEqual(capturedSort, { amount: -1 });
  assert.equal(capturedLimit, 25);
});

test("listForOwnerFiltered: omits optional clauses and defaults sort to newest", async (t) => {
  let capturedFilter: Record<string, unknown> = {};
  let capturedSort: unknown;
  const fakeChain = {
    sort: (s: unknown) => { capturedSort = s; return fakeChain; },
    limit: () => fakeChain,
    lean: async () => []
  };
  patch(
    Transaction,
    "find",
    ((filter: Record<string, unknown>) => { capturedFilter = filter; return fakeChain; }) as unknown as typeof Transaction.find,
    t
  );

  await mongoTransactionRepository.listForOwnerFiltered({ ownerId: OWNER_OID, limit: 10 });

  assert.deepEqual(capturedFilter, { ownerId: OWNER_OID });
  assert.deepEqual(capturedSort, { createdAt: -1 });
});

// ---------------------------------------------------------------------------
// recentForOwner / lastForOwner
// ---------------------------------------------------------------------------

test("recentForOwner: sorts newest-first, applies type and date window", async (t) => {
  let capturedFilter: Record<string, unknown> = {};
  let capturedSort: unknown;
  let capturedLimit = -1;
  const fakeChain = {
    sort: (s: unknown) => { capturedSort = s; return fakeChain; },
    limit: (n: number) => { capturedLimit = n; return fakeChain; },
    lean: async () => [leanTx]
  };
  patch(
    Transaction,
    "find",
    ((filter: Record<string, unknown>) => { capturedFilter = filter; return fakeChain; }) as unknown as typeof Transaction.find,
    t
  );

  const records = await mongoTransactionRepository.recentForOwner({
    ownerId: OWNER_OID,
    type: "credit",
    dateFrom: new Date("2026-06-01T00:00:00.000Z"),
    limit: 5
  });

  assert.equal(records.length, 1);
  assert.equal(records[0].id, leanTx._id);
  assert.equal(capturedFilter.ownerId, OWNER_OID);
  assert.equal(capturedFilter.type, "credit");
  assert.ok(capturedFilter.createdAt);
  assert.deepEqual(capturedSort, { createdAt: -1 });
  assert.equal(capturedLimit, 5);
});

test("lastForOwner: returns the single newest matching record", async (t) => {
  let capturedLimit = -1;
  const fakeChain = {
    sort: () => fakeChain,
    limit: (n: number) => { capturedLimit = n; return fakeChain; },
    lean: async () => [leanTx]
  };
  patch(Transaction, "find", ((_f: unknown) => fakeChain) as unknown as typeof Transaction.find, t);

  const record = await mongoTransactionRepository.lastForOwner({ ownerId: OWNER_OID, type: "debit" });

  assert.ok(record);
  assert.equal(record?.id, leanTx._id);
  assert.equal(capturedLimit, 1);
});

test("lastForOwner: returns null when nothing matches", async (t) => {
  const fakeChain = {
    sort: () => fakeChain,
    limit: () => fakeChain,
    lean: async () => []
  };
  patch(Transaction, "find", ((_f: unknown) => fakeChain) as unknown as typeof Transaction.find, t);

  const record = await mongoTransactionRepository.lastForOwner({ ownerId: OWNER_OID, type: "debit" });

  assert.equal(record, null);
});

// ---------------------------------------------------------------------------
// hasDebitToCounterparty
// ---------------------------------------------------------------------------

test("hasDebitToCounterparty: true when a debit exists", async (t) => {
  let capturedFilter: unknown;
  patch(
    Transaction,
    "exists",
    (((filter: unknown) => { capturedFilter = filter; return Promise.resolve({ _id: "x" }); }) as unknown) as typeof Transaction.exists,
    t
  );

  const result = await mongoTransactionRepository.hasDebitToCounterparty({
    ownerId: OWNER_OID,
    counterpartyEmail: "bob@example.com"
  });

  assert.equal(result, true);
  assert.deepEqual(capturedFilter, {
    ownerId: OWNER_OID,
    counterpartyEmail: "bob@example.com",
    type: "debit"
  });
});

test("hasDebitToCounterparty: false when no debit exists", async (t) => {
  patch(
    Transaction,
    "exists",
    (((_filter: unknown) => Promise.resolve(null)) as unknown) as typeof Transaction.exists,
    t
  );

  const result = await mongoTransactionRepository.hasDebitToCounterparty({
    ownerId: OWNER_OID,
    counterpartyEmail: "bob@example.com"
  });

  assert.equal(result, false);
});
