// Generated by OrchestKit Claude Plugin
// Created: 2026-06-22

import type { TransactionRepository } from "../types.js";
import { stubRepository } from "./stub.js";

export const mongoTransactionRepository = stubRepository<TransactionRepository>("mongoTransactionRepository");
