// Generated by OrchestKit Claude Plugin
// Created: 2026-06-22

// src/repositories/mongo/transaction.repository.test.ts
import assert from "node:assert/strict";
import test from "node:test";
import { Types } from "mongoose";
import { Transaction } from "../../models/Transaction.js";
import { mongoTransactionRepository } from "./transaction.repository.js";

function patch<T extends object, K extends keyof T>(o: T, k: K, v: T[K], t: test.TestContext) {
  const orig = o[k]; o[k] = v; t.after(() => { o[k] = orig; });
}

const OWNER_OID = "507f1f77bcf86cd799439011";

const leanTx = {
  _id: "60d5ec49f1b2c8a1f8e4e1b1",
  ownerId: OWNER_OID,
  counterpartyEmail: "bob@example.com",
  amount: 100,
  type: "debit",
  directionLabel: "Sent",
  reason: "lunch",
  enteredCurrency: undefined,
  enteredAmount: undefined,
  exchangeRateUsed: undefined,
  exchangeRateFetchedAt: undefined,
  createdAt: new Date("2026-06-01T12:00:00.000Z"),
  updatedAt: new Date("2026-06-01T12:00:00.000Z")
};

// ---------------------------------------------------------------------------
// createMany
// ---------------------------------------------------------------------------

test("createMany: calls Transaction.create with session and returns records", async (t) => {
  let capturedDocs: unknown;
  let capturedOpts: unknown;
  patch(
    Transaction,
    "create",
    (async (docs: unknown, opts: unknown) => {
      capturedDocs = docs;
      capturedOpts = opts;
      return [{ ...leanTx, toObject: () => leanTx }];
    }) as unknown as typeof Transaction.create,
    t
  );

  const input = [{
    ownerId: OWNER_OID,
    counterpartyEmail: "bob@example.com",
    amount: 100,
    type: "debit" as const,
    directionLabel: "Sent",
    reason: "lunch"
  }];
  const records = await mongoTransactionRepository.createMany(input);

  assert.equal(records.length, 1);
  assert.equal(records[0].id, leanTx._id);
  assert.equal((records[0] as Record<string, unknown>)._id, undefined);
  assert.equal(records[0].ownerId, OWNER_OID);
  assert.ok(Array.isArray(capturedDocs));
  assert.deepEqual((capturedOpts as Record<string, unknown>).ordered, true);
});

// ---------------------------------------------------------------------------
// listForOwner
// ---------------------------------------------------------------------------

test("listForOwner: returns TransactionRecords with string id", async (t) => {
  const fakeChain = {
    sort: () => fakeChain,
    skip: () => fakeChain,
    limit: () => fakeChain,
    lean: async () => [leanTx]
  };
  patch(
    Transaction,
    "find",
    ((_filter: unknown) => fakeChain) as unknown as typeof Transaction.find,
    t
  );
  patch(
    Transaction,
    "countDocuments",
    (async (_filter: unknown) => 1) as unknown as typeof Transaction.countDocuments,
    t
  );

  const { transactions, total } = await mongoTransactionRepository.listForOwner({
    ownerId: OWNER_OID,
    page: 1,
    limit: 10
  });

  assert.equal(total, 1);
  assert.equal(transactions.length, 1);
  assert.equal(transactions[0].id, leanTx._id);
  assert.equal((transactions[0] as Record<string, unknown>)._id, undefined);
});

test("listForOwner: skip is (page-1)*limit", async (t) => {
  let capturedSkip = -1;
  let capturedLimit = -1;
  const fakeChain = {
    sort: () => fakeChain,
    skip: (n: number) => { capturedSkip = n; return fakeChain; },
    limit: (n: number) => { capturedLimit = n; return fakeChain; },
    lean: async () => []
  };
  patch(Transaction, "find", ((_f: unknown) => fakeChain) as unknown as typeof Transaction.find, t);
  patch(Transaction, "countDocuments", (async () => 0) as unknown as typeof Transaction.countDocuments, t);

  await mongoTransactionRepository.listForOwner({ ownerId: OWNER_OID, page: 3, limit: 5 });
  assert.equal(capturedSkip, 10);
  assert.equal(capturedLimit, 5);
});

// ---------------------------------------------------------------------------
// recentWithCounterparty
// ---------------------------------------------------------------------------

test("recentWithCounterparty: returns TransactionRecords sorted desc", async (t) => {
  let capturedFilter: unknown;
  let capturedLimit = -1;
  let capturedSort: unknown;
  const fakeChain = {
    sort: (s: unknown) => { capturedSort = s; return fakeChain; },
    limit: (n: number) => { capturedLimit = n; return fakeChain; },
    lean: async () => [leanTx]
  };
  patch(
    Transaction,
    "find",
    ((filter: unknown) => { capturedFilter = filter; return fakeChain; }) as unknown as typeof Transaction.find,
    t
  );

  const records = await mongoTransactionRepository.recentWithCounterparty({
    ownerId: OWNER_OID,
    counterpartyEmail: "bob@example.com",
    limit: 5
  });

  assert.equal(records.length, 1);
  assert.equal(records[0].id, leanTx._id);
  assert.deepEqual(capturedFilter, { ownerId: OWNER_OID, counterpartyEmail: "bob@example.com" });
  assert.deepEqual(capturedSort, { createdAt: -1 });
  assert.equal(capturedLimit, 5);
});

// ---------------------------------------------------------------------------
// getRelationshipStats
// ---------------------------------------------------------------------------

test("getRelationshipStats: $match uses Types.ObjectId for ownerId", async (t) => {
  let capturedPipeline: unknown[] = [];
  patch(
    Transaction,
    "aggregate",
    (async (pipeline: unknown[]) => { capturedPipeline = pipeline; return []; }) as unknown as typeof Transaction.aggregate,
    t
  );

  await mongoTransactionRepository.getRelationshipStats({
    ownerId: OWNER_OID,
    counterpartyEmail: "bob@example.com"
  });

  const match = (capturedPipeline[0] as { $match: Record<string, unknown> }).$match;
  // The ObjectId cast must live in the repo, not in the consumer
  assert.ok(match.ownerId instanceof Types.ObjectId, "ownerId must be a Types.ObjectId");
  assert.equal(String(match.ownerId), OWNER_OID);
  assert.equal(match.counterpartyEmail, "bob@example.com");
});

test("getRelationshipStats: returns correct fields from aggregate result", async (t) => {
  patch(
    Transaction,
    "aggregate",
    (async () => [{
      totalSent: 500,
      totalReceived: 200.5,
      transactionCount: 7,
      lastTransactionAt: new Date("2026-06-10T08:00:00.000Z")
    }]) as unknown as typeof Transaction.aggregate,
    t
  );

  const result = await mongoTransactionRepository.getRelationshipStats({
    ownerId: OWNER_OID,
    counterpartyEmail: "bob@example.com"
  });

  assert.equal(result.totalSent, 500);
  assert.equal(result.totalReceived, 200.5);
  assert.equal(result.transactionCount, 7);
  assert.deepEqual(result.lastTransactionAt, new Date("2026-06-10T08:00:00.000Z"));
});

test("getRelationshipStats: returns zero-defaults when aggregate is empty", async (t) => {
  patch(Transaction, "aggregate", (async () => []) as unknown as typeof Transaction.aggregate, t);

  const result = await mongoTransactionRepository.getRelationshipStats({
    ownerId: OWNER_OID,
    counterpartyEmail: "bob@example.com"
  });

  assert.equal(result.totalSent, 0);
  assert.equal(result.totalReceived, 0);
  assert.equal(result.transactionCount, 0);
  assert.equal(result.lastTransactionAt, null);
});

// ---------------------------------------------------------------------------
// getDirectionalTotals
// ---------------------------------------------------------------------------

test("getDirectionalTotals: $match uses Types.ObjectId for ownerId", async (t) => {
  let capturedPipeline: unknown[] = [];
  patch(
    Transaction,
    "aggregate",
    (async (pipeline: unknown[]) => { capturedPipeline = pipeline; return []; }) as unknown as typeof Transaction.aggregate,
    t
  );

  await mongoTransactionRepository.getDirectionalTotals({
    ownerId: OWNER_OID,
    counterpartyEmail: "bob@example.com"
  });

  const match = (capturedPipeline[0] as { $match: Record<string, unknown> }).$match;
  assert.ok(match.ownerId instanceof Types.ObjectId, "ownerId must be a Types.ObjectId");
  assert.equal(String(match.ownerId), OWNER_OID);
});

test("getDirectionalTotals: returns credit/debit totals and counts", async (t) => {
  patch(
    Transaction,
    "aggregate",
    (async () => [
      { _id: "credit", total: 300, count: 3 },
      { _id: "debit", total: 150, count: 2 }
    ]) as unknown as typeof Transaction.aggregate,
    t
  );

  const result = await mongoTransactionRepository.getDirectionalTotals({
    ownerId: OWNER_OID,
    counterpartyEmail: "bob@example.com"
  });

  assert.equal(result.creditTotal, 300);
  assert.equal(result.creditCount, 3);
  assert.equal(result.debitTotal, 150);
  assert.equal(result.debitCount, 2);
});

test("getDirectionalTotals: returns zeros when aggregate is empty", async (t) => {
  patch(Transaction, "aggregate", (async () => []) as unknown as typeof Transaction.aggregate, t);

  const result = await mongoTransactionRepository.getDirectionalTotals({
    ownerId: OWNER_OID,
    counterpartyEmail: "bob@example.com"
  });

  assert.equal(result.creditTotal, 0);
  assert.equal(result.creditCount, 0);
  assert.equal(result.debitTotal, 0);
  assert.equal(result.debitCount, 0);
});

// ---------------------------------------------------------------------------
// sumSameDayDebits
// ---------------------------------------------------------------------------

test("sumSameDayDebits: returns sum of debit amounts in day window", async (t) => {
  const dayStart = new Date("2026-06-22T00:00:00.000Z");
  const dayEnd = new Date("2026-06-23T00:00:00.000Z");

  let capturedFilter: unknown;
  const fakeChain = {
    select: () => fakeChain,
    session: () => fakeChain,
    lean: async () => [{ amount: 100 }, { amount: 50.5 }]
  };
  patch(
    Transaction,
    "find",
    ((filter: unknown) => { capturedFilter = filter; return fakeChain; }) as unknown as typeof Transaction.find,
    t
  );

  const result = await mongoTransactionRepository.sumSameDayDebits({
    ownerId: OWNER_OID,
    dayStart,
    dayEnd
  });

  assert.equal(result, 150.5);
  const filter = capturedFilter as Record<string, unknown>;
  assert.equal(filter.ownerId, OWNER_OID);
  assert.equal(filter.type, "debit");
});

test("sumSameDayDebits: returns 0 when no debits found", async (t) => {
  const fakeChain = {
    select: () => fakeChain,
    session: () => fakeChain,
    lean: async () => []
  };
  patch(Transaction, "find", ((_f: unknown) => fakeChain) as unknown as typeof Transaction.find, t);

  const result = await mongoTransactionRepository.sumSameDayDebits({
    ownerId: OWNER_OID,
    dayStart: new Date("2026-06-22T00:00:00.000Z"),
    dayEnd: new Date("2026-06-23T00:00:00.000Z")
  });

  assert.equal(result, 0);
});
