// Generated by OrchestKit Claude Plugin
// Created: 2026-06-22

import type { UserRepository } from "../types.js";
import { stubRepository } from "./stub.js";

export const mongoUserRepository = stubRepository<UserRepository>("mongoUserRepository");
