// Generated by OrchestKit Claude Plugin
// Created: 2026-06-22

// src/repositories/mongo/user.repository.test.ts
import assert from "node:assert/strict";
import test from "node:test";
import { User } from "../../models/User.js";
import { mongoUserRepository } from "./user.repository.js";

function patch<T extends object, K extends keyof T>(o: T, k: K, v: T[K], t: test.TestContext) {
  const orig = o[k]; o[k] = v; t.after(() => { o[k] = orig; });
}

const ID = "507f1f77bcf86cd799439011";
const lean = {
  _id: ID, email: "a@b.com", passwordHash: "h", phone: "+972", isVerified: true,
  personalDetails: null, verificationTokenHash: null, verificationTokenExpiresAt: null,
  balance: 100, role: "user", createdAt: new Date(0), updatedAt: new Date(0)
};

test("findById maps a lean doc to a UserRecord with string id", async (t) => {
  patch(User, "findById", ((id: string) => ({ lean: async () => (id === ID ? lean : null) })) as never, t);
  const rec = await mongoUserRepository.findById(ID);
  assert.equal(rec?.id, ID);
  assert.equal(rec?.balance, 100);
  assert.equal((rec as Record<string, unknown>)._id, undefined);
});

test("findByIdSafe omits secret fields", async (t) => {
  patch(User, "findById", (() => ({ lean: async () => lean })) as never, t);
  const rec = await mongoUserRepository.findByIdSafe(ID);
  assert.equal((rec as Record<string, unknown>).passwordHash, undefined);
  assert.equal((rec as Record<string, unknown>).verificationTokenHash, undefined);
  assert.equal(rec?.email, "a@b.com");
});

test("create maps a duplicate-key (E11000) to DuplicateKeyError", async (t) => {
  patch(User, "create", (async () => { const e = new Error("dup") as Error & { code: number }; e.code = 11000; throw e; }) as never, t);
  await assert.rejects(
    () => mongoUserRepository.create({ email: "a@b.com", passwordHash: "h", phone: "+972", balance: 0 }),
    (e: unknown) => (e as Error).name === "DuplicateKeyError"
  );
});
