// Generated by OrchestKit Claude Plugin
// Created: 2026-06-22

import type { VideoAuditLogRepository } from "../types.js";
import { stubRepository } from "./stub.js";

export const mongoVideoAuditLogRepository = stubRepository<VideoAuditLogRepository>("mongoVideoAuditLogRepository");
