// Generated by OrchestKit Claude Plugin
// Created: 2026-06-22

import type { VideoSessionRepository } from "../types.js";
import { stubRepository } from "./stub.js";

export const mongoVideoSessionRepository = stubRepository<VideoSessionRepository>("mongoVideoSessionRepository");
