// Generated by OrchestKit Claude Plugin
// Created: 2026-06-23

// src/repositories/mongo/videoSession.repository.test.ts
import assert from "node:assert/strict";
import test from "node:test";
import { VideoSession } from "../../models/VideoSession.js";
import { mongoVideoSessionRepository } from "./videoSession.repository.js";

function patch<T extends object, K extends keyof T>(o: T, k: K, v: T[K], t: test.TestContext) {
  const orig = o[k];
  o[k] = v;
  t.after(() => { o[k] = orig; });
}

const SESSION_OID = "507f1f77bcf86cd799439099";
const USER_OID   = "507f1f77bcf86cd799439011";
const AGENT_OID  = "507f1f77bcf86cd799439012";

const leanSession = {
  _id: SESSION_OID,
  userId: USER_OID,
  assignedAgentId: null,
  type: "support",
  status: "waiting_for_agent",
  roomName: "virly-support-abc123",
  provider: "jitsi-public-demo",
  topic: null,
  userProblemSummary: null,
  startedAt: null,
  endedAt: null,
  userJoinedAt: null,
  agentJoinedAt: null,
  metadata: { userAgent: null, locale: null, source: "dashboard" },
  createdAt: new Date("2026-01-01T00:00:00.000Z"),
  updatedAt: new Date("2026-01-01T00:00:00.000Z")
};

// ---------------------------------------------------------------------------
// findById
// ---------------------------------------------------------------------------

test("findById: maps lean doc to record — id is string, no _id leaked", async (t) => {
  const chain = { session: () => chain, lean: async () => leanSession };
  patch(VideoSession, "findOne", ((_f: unknown) => chain) as unknown as typeof VideoSession.findOne, t);

  const rec = await mongoVideoSessionRepository.findById(SESSION_OID);
  assert.ok(rec);
  assert.equal(rec.id, SESSION_OID);
  assert.equal((rec as Record<string, unknown>)._id, undefined, "must not leak _id");
  assert.equal(rec.userId, USER_OID);
  assert.equal(rec.assignedAgentId, null);
  assert.equal(rec.status, "waiting_for_agent");
});

test("findById: queries by _id", async (t) => {
  let captured: unknown;
  const chain = { session: () => chain, lean: async () => null };
  patch(VideoSession, "findOne", ((f: unknown) => { captured = f; return chain; }) as unknown as typeof VideoSession.findOne, t);

  await mongoVideoSessionRepository.findById(SESSION_OID);
  assert.deepEqual(captured, { _id: SESSION_OID });
});

test("findById: returns null for malformed id without touching model", async (t) => {
  let called = false;
  patch(VideoSession, "findOne", (() => { called = true; return { session: () => ({}), lean: async () => null }; }) as unknown as typeof VideoSession.findOne, t);

  const rec = await mongoVideoSessionRepository.findById("not-an-oid");
  assert.equal(rec, null);
  assert.equal(called, false, "must short-circuit invalid ids");
});

test("findById: passes session when tx provided", async (t) => {
  let captured: unknown;
  const fakeSession = { id: "s1" };
  const chain = { session(s: unknown) { captured = s; return chain; }, lean: async () => leanSession };
  patch(VideoSession, "findOne", ((_f: unknown) => chain) as unknown as typeof VideoSession.findOne, t);

  await mongoVideoSessionRepository.findById(SESSION_OID, fakeSession);
  assert.equal(captured, fakeSession);
});

test("findById: stringifies non-null assignedAgentId", async (t) => {
  const withAgent = { ...leanSession, assignedAgentId: { toString: () => AGENT_OID } };
  const chain = { session: () => chain, lean: async () => withAgent };
  patch(VideoSession, "findOne", ((_f: unknown) => chain) as unknown as typeof VideoSession.findOne, t);

  const rec = await mongoVideoSessionRepository.findById(SESSION_OID);
  assert.ok(rec);
  assert.equal(rec.assignedAgentId, AGENT_OID);
});

// ---------------------------------------------------------------------------
// findByRoomName
// ---------------------------------------------------------------------------

test("findByRoomName: queries by roomName and maps record", async (t) => {
  let captured: unknown;
  const chain = { session: () => chain, lean: async () => leanSession };
  patch(VideoSession, "findOne", ((f: unknown) => { captured = f; return chain; }) as unknown as typeof VideoSession.findOne, t);

  const rec = await mongoVideoSessionRepository.findByRoomName("virly-support-abc123");
  assert.ok(rec);
  assert.equal(rec.roomName, "virly-support-abc123");
  assert.deepEqual(captured, { roomName: "virly-support-abc123" });
});

// ---------------------------------------------------------------------------
// create
// ---------------------------------------------------------------------------

test("create: inserts and returns a record (toObject path)", async (t) => {
  let capturedDocs: unknown;
  patch(
    VideoSession,
    "create",
    (async (docs: unknown, _opts: unknown) => {
      capturedDocs = docs;
      return [{ ...leanSession, toObject: () => leanSession }];
    }) as unknown as typeof VideoSession.create,
    t
  );

  const rec = await mongoVideoSessionRepository.create({
    userId: USER_OID,
    assignedAgentId: null,
    type: "support",
    status: "waiting_for_agent",
    roomName: "virly-support-abc123",
    provider: "jitsi-public-demo",
    topic: null,
    userProblemSummary: null,
    startedAt: null,
    endedAt: null,
    userJoinedAt: null,
    agentJoinedAt: null,
    metadata: { userAgent: null, locale: null, source: "dashboard" }
  });

  assert.ok(rec);
  assert.equal(rec.id, SESSION_OID);
  assert.equal((rec as Record<string, unknown>)._id, undefined);
  assert.ok(Array.isArray(capturedDocs), "create receives an array (ordered insert)");
});

test("create: passes session in options when tx provided", async (t) => {
  let capturedOpts: Record<string, unknown> = {};
  const fakeSession = { id: "s1" };
  patch(
    VideoSession,
    "create",
    (async (_docs: unknown, opts: Record<string, unknown>) => {
      capturedOpts = opts;
      return [{ ...leanSession, toObject: () => leanSession }];
    }) as unknown as typeof VideoSession.create,
    t
  );

  await mongoVideoSessionRepository.create(
    {
      userId: USER_OID, assignedAgentId: null, type: "support",
      status: "waiting_for_agent", roomName: "virly-support-abc123",
      provider: "jitsi-public-demo", topic: null, userProblemSummary: null,
      startedAt: null, endedAt: null, userJoinedAt: null, agentJoinedAt: null,
      metadata: { userAgent: null, locale: null, source: "dashboard" }
    },
    fakeSession
  );
  assert.equal(capturedOpts.session, fakeSession);
});

// ---------------------------------------------------------------------------
// update
// ---------------------------------------------------------------------------

test("update: calls findOneAndUpdate with $set patch and { new: true }", async (t) => {
  let capturedFilter: unknown;
  let capturedUpdate: unknown;
  let capturedOpts: Record<string, unknown> = {};
  patch(
    VideoSession,
    "findOneAndUpdate",
    (async (f: unknown, u: unknown, o: Record<string, unknown>) => {
      capturedFilter = f; capturedUpdate = u; capturedOpts = o;
      return { ...leanSession, status: "active", toObject: () => ({ ...leanSession, status: "active" }) };
    }) as unknown as typeof VideoSession.findOneAndUpdate,
    t
  );

  const rec = await mongoVideoSessionRepository.update(SESSION_OID, { status: "active" });
  assert.ok(rec);
  assert.equal(rec.status, "active");
  assert.deepEqual(capturedFilter, { _id: SESSION_OID });
  assert.deepEqual((capturedUpdate as Record<string, unknown>).$set, { status: "active" });
  assert.equal(capturedOpts.new, true);
});

test("update: returns null for malformed id", async (t) => {
  let called = false;
  patch(VideoSession, "findOneAndUpdate", (async () => { called = true; return null; }) as unknown as typeof VideoSession.findOneAndUpdate, t);

  const rec = await mongoVideoSessionRepository.update("bad-id", { status: "active" });
  assert.equal(rec, null);
  assert.equal(called, false);
});

test("update: returns null when no doc matches", async (t) => {
  patch(VideoSession, "findOneAndUpdate", (async () => null) as unknown as typeof VideoSession.findOneAndUpdate, t);

  const rec = await mongoVideoSessionRepository.update(SESSION_OID, { status: "active" });
  assert.equal(rec, null);
});

// ---------------------------------------------------------------------------
// listForUser
// ---------------------------------------------------------------------------

test("listForUser: filters by userId and sorts newest-first", async (t) => {
  let capturedFilter: unknown;
  let sortSpec: unknown;
  const chain = {
    sort(s: unknown) { sortSpec = s; return chain; },
    session: () => chain,
    lean: async () => [leanSession]
  };
  patch(VideoSession, "find", ((f: unknown) => { capturedFilter = f; return chain; }) as unknown as typeof VideoSession.find, t);

  const recs = await mongoVideoSessionRepository.listForUser(USER_OID);
  assert.equal(recs.length, 1);
  assert.equal(recs[0].id, SESSION_OID);
  assert.equal((recs[0] as Record<string, unknown>)._id, undefined);
  assert.deepEqual(capturedFilter, { userId: USER_OID });
  assert.deepEqual(sortSpec, { createdAt: -1 });
});

// ---------------------------------------------------------------------------
// listActiveForType
// ---------------------------------------------------------------------------

test("listActiveForType: filters by type and active statuses (requested/waiting_for_agent/active)", async (t) => {
  let capturedFilter: Record<string, unknown> = {};
  const chain = {
    sort: () => chain,
    session: () => chain,
    lean: async () => [leanSession]
  };
  patch(VideoSession, "find", ((f: Record<string, unknown>) => { capturedFilter = f; return chain; }) as unknown as typeof VideoSession.find, t);

  const recs = await mongoVideoSessionRepository.listActiveForType("support");
  assert.equal(recs.length, 1);
  assert.equal(capturedFilter.type, "support");
  const statusIn = (capturedFilter.status as { $in: string[] }).$in;
  assert.ok(statusIn.includes("requested"), "must include requested");
  assert.ok(statusIn.includes("waiting_for_agent"), "must include waiting_for_agent");
  assert.ok(statusIn.includes("active"), "must include active");
  assert.equal(statusIn.includes("ended"), false, "must exclude terminal statuses");
  assert.equal(statusIn.includes("cancelled"), false);
  assert.equal(statusIn.includes("failed"), false);
  assert.equal(statusIn.includes("missed"), false);
});
