// Generated by OrchestKit Claude Plugin
// Created: 2026-06-14

/**
 * `executeTransfer` — the ONLY node that moves money (design §4.1 / Phase 5).
 *
 * Reached only from the human-confirmed resume path of `transferGate`. It calls
 * the backend transfer service (`respondToAiPendingTransfer` →
 * `executeTransferWithSession`, in a Mongo transaction) for the card the user
 * confirmed, then surfaces the truthful outcome.
 */
import type { LangGraphRunnableConfig } from "@langchain/langgraph";

import { respondToAiPendingTransfer } from "../../../services/aiPendingTransfer.service.js";
import { getConfigurable } from "../toolContext.js";
import type { V2AgentStateType } from "../state.js";

export async function executeTransferNode(
  state: V2AgentStateType,
  config: LangGraphRunnableConfig
): Promise<Partial<V2AgentStateType>> {
  const cfg = getConfigurable(config);
  const card = state.confirmation;
  if (!card) {
    return { responseMessage: "There was no transfer to execute." };
  }

  const respond = cfg.transferResponseService ?? respondToAiPendingTransfer;
  const result = await respond({
    userId: cfg.userId,
    pendingTransferId: card.id,
    action: "confirm",
    version: state.resumeMeta?.version ?? card.version,
    idempotencyKey: state.resumeMeta?.idempotencyKey
  });

  return {
    transferResult: result,
    responseMessage:
      cfg.locale === "he"
        ? `בוצע — ₪${card.amount} בדרך ל-${card.recipientEmail}. ✅`
        : `Done — ₪${card.amount} is on its way to ${card.recipientEmail}.`
  };
}
