// Generated by OrchestKit Claude Plugin
// Created: 2026-06-14

/**
 * `transferGate` — STUB (Phase 5).
 *
 * In the full design this node handles the money-proposing tools by validating
 * the transfer, building the card, and calling `interrupt({ type, card })` so the
 * graph pauses for the human-confirmed resume (`Command`) — the ONLY path that
 * reaches `executeTransferWithSession`. None of that is wired yet.
 *
 * In Phases 0–4 the money tools run inside the ordinary ToolNode and only
 * *prepare* a card (no funds move, no interrupt, no execution). This stub exists
 * so the topology seam is visible; the read-only route never reaches it.
 */
import type { LangGraphRunnableConfig } from "@langchain/langgraph";

import type { V2AgentStateType } from "../state.js";

export async function transferGateNode(
  _state: V2AgentStateType,
  _config: LangGraphRunnableConfig
): Promise<Partial<V2AgentStateType>> {
  // Phase 5: validate -> build card -> interrupt -> resume -> executeTransfer.
  return {};
}
