// Generated by OrchestKit Claude Plugin
// Created: 2026-06-23

import assert from "node:assert/strict";
import test from "node:test";
import { readdir, readFile } from "node:fs/promises";
import path from "node:path";

const ROOT = path.resolve(import.meta.dirname, "..");
const ALLOWED_PREFIXES = [
  path.join(ROOT, "repositories", "mongo"),
  path.join(ROOT, "ai", "evals")
];

async function walk(dir: string): Promise<string[]> {
  const out: string[] = [];
  for (const e of await readdir(dir, { withFileTypes: true })) {
    const p = path.join(dir, e.name);
    if (e.isDirectory()) out.push(...await walk(p));
    else if (e.name.endsWith(".ts") && !e.name.endsWith(".test.ts")) out.push(p);
  }
  return out;
}

test("only repositories/mongo and ai/evals import ../models/*", async () => {
  const offenders: string[] = [];
  for (const file of await walk(ROOT)) {
    if (ALLOWED_PREFIXES.some((prefix) => file.startsWith(prefix))) continue;
    const src = await readFile(file, "utf8");
    if (/from\s+["'](\.\.\/)*models\//.test(src)) offenders.push(path.relative(ROOT, file));
  }
  assert.deepEqual(offenders, [], `Files still importing models directly: ${offenders.join(", ")}`);
});
