// Generated by OrchestKit Claude Plugin
// Created: 2026-06-22

// src/repositories/registry.ts
import type { Repositories } from "./types.js";
import { createMongoRepositories } from "./mongo/index.js";

export function createRepositories(driver: "mongo" | "postgres"): Repositories {
  if (driver === "mongo") return createMongoRepositories();
  throw new Error(`Driver "${driver}" not implemented yet (added in Plan 2).`);
}
