// Generated by OrchestKit Claude Plugin
// Created: 2026-06-14

/**
 * Long-term (cross-conversation) memory types for the v2 assistant.
 *
 * These describe the durable, per-user facts the assistant carries between
 * conversations — the "it remembers me" layer (design §6.3). They live in a
 * LangGraph `Store` namespaced by `userId`; `prepare` hydrates a
 * {@link LongTermMemorySnapshot} into the system prompt and `persist` upserts
 * what was learned this turn.
 */

/** A person the user has transacted with, remembered across conversations. */
export type CounterpartyRecord = {
  /** Authoritative email (the store is server-side; not exposed verbatim to UI). */
  email: string;
  displayName?: string;
  relation: "sent_to" | "received_from" | "both";
  /** ISO timestamp of the most recent interaction we know about. */
  lastInteractionAt?: string;
};

/** Durable user preferences that shape how the assistant behaves. */
export type UserPreferences = {
  preferredLanguage?: "he" | "en";
  defaultAssistantId?: string;
  /** "always ask before sending over X" — informational in read-only phases. */
  confirmAboveAmount?: number;
};

/** A salient free-text fact the user stated ("my rent is the 1st"). */
export type SalientFact = {
  id: string;
  text: string;
  createdAt: string;
};

/** The hydrated view of long-term memory injected into a turn's prompt. */
export type LongTermMemorySnapshot = {
  counterparties: CounterpartyRecord[];
  preferences: UserPreferences;
  facts: SalientFact[];
};

export function emptyLongTermMemorySnapshot(): LongTermMemorySnapshot {
  return { counterparties: [], preferences: {}, facts: [] };
}
