// Generated by OrchestKit Claude Plugin
// Created: 2026-06-13

import type { AmountExpr } from "./state.js";

/**
 * Rounds a money value to two decimal places using round-half-up, guarding
 * against binary floating-point representation error (e.g. 31.205 -> 31.21).
 */
function roundToCents(value: number): number {
  return Math.round((value + Number.EPSILON) * 100) / 100;
}

/**
 * Deterministically evaluates a compositional amount expression.
 *
 * The caller resolves `expr.base` to a concrete `baseValue`; this function owns
 * the arithmetic and the money-value guarantees. It is the single source of all
 * transfer amount arithmetic — the LLM never produces a money value.
 *
 * @param baseValue the already-resolved value of `expr.base` (must be > 0).
 * @param expr the arithmetic to apply.
 * @returns the resulting amount, rounded to two decimals (always > 0).
 * @throws if inputs are invalid (non-positive base, missing/non-finite operand,
 *         division by zero, or a non-positive result).
 */
export function evaluateAmountExpr(baseValue: number, expr: AmountExpr): number {
  if (!Number.isFinite(baseValue) || baseValue <= 0) {
    throw new Error(
      `evaluateAmountExpr: base value must be a positive finite number, got ${baseValue}`
    );
  }

  if (!expr.op) {
    return roundToCents(baseValue);
  }

  const { op, operand } = expr;
  if (operand == null || !Number.isFinite(operand)) {
    throw new Error(
      `evaluateAmountExpr: op "${op}" requires a finite operand, got ${operand}`
    );
  }

  let raw: number;
  switch (op) {
    case "mul":
      raw = baseValue * operand;
      break;
    case "div":
      if (operand === 0) {
        throw new Error("evaluateAmountExpr: division by zero");
      }
      raw = baseValue / operand;
      break;
    case "add":
      raw = baseValue + operand;
      break;
    case "sub":
      raw = baseValue - operand;
      break;
    default: {
      const exhaustive: never = op;
      throw new Error(`evaluateAmountExpr: unsupported op ${String(exhaustive)}`);
    }
  }

  const result = roundToCents(raw);
  if (!Number.isFinite(result) || result <= 0) {
    throw new Error(
      `evaluateAmountExpr: result must be a positive finite number, got ${result}`
    );
  }

  return result;
}
