// Generated by OrchestKit Claude Plugin
// Created: 2026-06-13

import assert from "node:assert/strict";
import test from "node:test";
import { AIMessage, HumanMessage } from "@langchain/core/messages";
import { createEmptyCounterpartyMemory } from "./counterpartyMemory.js";
import { runAssistantGraph } from "./graph.js";
import type {
  ConversationContext,
  ConversationSaveInput,
  ConversationStore,
  CounterpartyMemory,
  PendingConfirmationMemory,
  TransferModificationService,
  TransferPreparationService
} from "./state.js";

/**
 * Regression target for docs/ai-context-resolution-plan.md.
 *
 * The exact failing dialogue: a pending transfer of 62.41 ILS to sga@thunder.com
 * is the conversational anchor, and a second recipient deni@trailblazers.com is
 * mentioned. Each reference below is evaluated against that anchor state:
 *
 *   - "double it"                              => 124.82 to sga@thunder.com
 *   - "send this to deni@trailblazers.com"     => 62.41 to deni@trailblazers.com
 *   - "the same amount sga@thunder.com sent me"
 *        (while the active recipient is deni)  => recipient stays deni, amount 62.41 (F2)
 *   - "the amount we discussed"                => 62.41
 *
 * Every money value is produced by deterministic code; the model only supplies
 * references/expressions. These tests are skipped at the Phase 0 baseline and
 * un-skipped incrementally as the resolver lands (Phases 2 + 5).
 */

const USER_ID = "507f1f77bcf86cd799439011";
const SGA_EMAIL = "sga@thunder.com";
const DENI_EMAIL = "deni@trailblazers.com";
const ANCHOR_AMOUNT = 62.41;

function pendingConfirmation(
  recipientEmail: string,
  amount: number
): PendingConfirmationMemory {
  return {
    confirmationId: "pending-anchor",
    type: "transfer",
    status: "pending",
    createdAt: new Date().toISOString(),
    expiresAt: new Date(Date.now() + 600000).toISOString(),
    recipientEmail,
    amount,
    currency: "ILS",
    turnCreated: 1,
    version: 1
  };
}

function createStore(
  memory: CounterpartyMemory
): ConversationStore & { saved: ConversationSaveInput[] } {
  let context: ConversationContext = {
    messages: [new HumanMessage("anchor"), new AIMessage("anchor reply")],
    memory
  };
  const saved: ConversationSaveInput[] = [];
  return {
    saved,
    async load() {
      return context;
    },
    async save(input) {
      saved.push(input);
      context = { messages: input.messages, memory: input.memory };
    }
  };
}

function echoPreparationService(): TransferPreparationService {
  return async (input) => {
    const recipientEmail =
      input.draft.recipientEmail ?? input.resolvedCounterparty?.email;
    if (!recipientEmail || !input.draft.amount) {
      return { status: "needs_clarification", message: "missing details" };
    }
    return {
      status: "ready",
      confirmation: buildConfirmation(recipientEmail, input.draft.amount, 1)
    };
  };
}

function echoModificationService(): TransferModificationService {
  return async (input) => {
    const recipientEmail =
      input.modificationDraft.recipientEmail ??
      input.resolvedCounterparty?.email ??
      SGA_EMAIL;
    if (!input.modificationDraft.amount) {
      return { status: "needs_clarification", message: "missing amount" };
    }
    return {
      status: "ready",
      confirmation: buildConfirmation(recipientEmail, input.modificationDraft.amount, 2),
      supersededConfirmationId: input.activePendingTransferId
    };
  };
}

function buildConfirmation(recipientEmail: string, amount: number, version: number) {
  return {
    id: `pending-${version}`,
    version,
    type: "transfer" as const,
    status: "pending" as const,
    recipientEmail,
    recipientFirstName: null,
    recipientLastName: null,
    amount,
    currency: "ILS" as const,
    recipient: {
      email: recipientEmail,
      firstName: null,
      lastName: null,
      displayName: recipientEmail,
      verified: true
    },
    amountDetails: { value: amount, currency: "ILS" as const, formatted: `₪${amount}` },
    reason: null,
    warnings: [],
    expiresAt: new Date(Date.now() + 600000).toISOString(),
    confirmAction: {
      method: "POST" as const,
      path: `/api/ai/confirmations/pending-${version}`,
      body: { action: "confirm" as const, version }
    },
    denyAction: {
      method: "POST" as const,
      path: `/api/ai/confirmations/pending-${version}`,
      body: { action: "deny" as const, version }
    }
  };
}

test(
  '"double it" doubles the pending amount and keeps the recipient',
  { skip: "Phase 5 target — un-skip with the LLM turn-context resolver" },
  async () => {
    const store = createStore({
      ...createEmptyCounterpartyMemory(),
      mode: "transfer_confirmation_pending",
      pendingConfirmation: pendingConfirmation(SGA_EMAIL, ANCHOR_AMOUNT)
    });

    const result = await runAssistantGraph(
      { userId: USER_ID, conversationId: "scenario-double", message: "double it" },
      {
        conversationStore: store,
        transferPreparationService: echoPreparationService(),
        transferModificationService: echoModificationService()
      }
    );

    assert.equal(result.confirmation?.recipientEmail, SGA_EMAIL);
    assert.equal(result.confirmation?.amount, 124.82);
  }
);

test(
  '"send this to deni" reuses the pending amount for the new recipient',
  { skip: "Phase 5 target — un-skip with the LLM turn-context resolver" },
  async () => {
    const store = createStore({
      ...createEmptyCounterpartyMemory(),
      mode: "transfer_confirmation_pending",
      pendingConfirmation: pendingConfirmation(SGA_EMAIL, ANCHOR_AMOUNT)
    });

    const result = await runAssistantGraph(
      {
        userId: USER_ID,
        conversationId: "scenario-this",
        message: `send this to ${DENI_EMAIL}`
      },
      {
        conversationStore: store,
        transferPreparationService: echoPreparationService(),
        transferModificationService: echoModificationService()
      }
    );

    assert.equal(result.confirmation?.recipientEmail, DENI_EMAIL);
    assert.equal(result.confirmation?.amount, ANCHOR_AMOUNT);
  }
);

test(
  '"the same amount sga sent me" keeps the active recipient deni (F2)',
  { skip: "Phase 5 target — un-skip with the LLM turn-context resolver" },
  async () => {
    const store = createStore({
      ...createEmptyCounterpartyMemory(),
      mode: "transfer_confirmation_pending",
      pendingConfirmation: pendingConfirmation(DENI_EMAIL, ANCHOR_AMOUNT)
    });

    const result = await runAssistantGraph(
      {
        userId: USER_ID,
        conversationId: "scenario-f2",
        message: `the same amount ${SGA_EMAIL} sent me`
      },
      {
        conversationStore: store,
        transferPreparationService: echoPreparationService(),
        transferModificationService: echoModificationService()
      }
    );

    assert.equal(result.confirmation?.recipientEmail, DENI_EMAIL);
    assert.equal(result.confirmation?.amount, ANCHOR_AMOUNT);
  }
);

test(
  '"the amount we discussed" resolves to the anchor amount',
  { skip: "Phase 5 target — un-skip with the LLM turn-context resolver" },
  async () => {
    const store = createStore({
      ...createEmptyCounterpartyMemory(),
      mode: "transfer_confirmation_pending",
      pendingConfirmation: pendingConfirmation(SGA_EMAIL, ANCHOR_AMOUNT)
    });

    const result = await runAssistantGraph(
      {
        userId: USER_ID,
        conversationId: "scenario-discussed",
        message: "the amount we discussed"
      },
      {
        conversationStore: store,
        transferPreparationService: echoPreparationService(),
        transferModificationService: echoModificationService()
      }
    );

    assert.equal(result.confirmation?.amount, ANCHOR_AMOUNT);
  }
);
