// Generated by OrchestKit Claude Plugin
// Created: 2026-06-13

import { AIMessage, HumanMessage, type BaseMessage } from "@langchain/core/messages";

import type { StoredChatMessage } from "./state.js";

/**
 * Converts the persisted/on-disk message shape into in-graph LangChain
 * messages. User turns become `HumanMessage`, assistant turns become
 * `AIMessage`. This is the read side of the store boundary; the MongoDB
 * document shape (`{ role, content, createdAt }`) is unchanged.
 */
export function fromStored(stored: StoredChatMessage[]): BaseMessage[] {
  return stored.map((message) =>
    message.role === "assistant"
      ? new AIMessage({ content: message.content })
      : new HumanMessage({ content: message.content })
  );
}

/**
 * Converts in-graph LangChain messages back into the persisted/on-disk
 * shape. Only `human`/`ai` turns are persisted; `system`/`tool` messages
 * are intentionally dropped, preserving the pre-migration behavior where
 * neither was ever stored. `content` is coerced to a string (R4 guard) so
 * content-block arrays cannot break persistence.
 */
export function toStored(messages: BaseMessage[]): StoredChatMessage[] {
  const stored: StoredChatMessage[] = [];
  for (const message of messages) {
    const type = message.getType();
    if (type === "human") {
      stored.push({ role: "user", content: String(message.content) });
    } else if (type === "ai") {
      stored.push({ role: "assistant", content: String(message.content) });
    }
  }
  return stored;
}

/**
 * Lightweight `{ role, content }` projection used by the LLM prompt
 * builders. Identical to `toStored`, kept as a named export so call sites
 * read intentionally (prompt projection vs. persistence) and so prompt
 * output stays byte-identical to the pre-migration baseline.
 */
export function toProviderMessages(messages: BaseMessage[]): StoredChatMessage[] {
  return toStored(messages);
}
