// Generated by OrchestKit Claude Plugin
// Created: 2026-06-13

import assert from "node:assert/strict";
import test from "node:test";

import { AIMessage, HumanMessage } from "@langchain/core/messages";

import {
  createEmptyCounterpartyMemory,
  trimConversationMessages
} from "./counterpartyMemory.js";
import {
  buildClassifierPrompt,
  buildReferenceResolverPrompt,
  buildTransferDraftPrompt
} from "./llm.js";
import { fromStored, toProviderMessages } from "./messageMapping.js";
import type { StoredChatMessage } from "./state.js";

// ---------------------------------------------------------------------------
// Legacy-document load compatibility
//
// mongoConversationStore.load deserializes the persisted `{ role, content,
// createdAt }` documents into BaseMessage[] via fromStored + trim. There is no
// mongodb-memory-server in this workspace, so we exercise that exact conversion
// against a legacy-shaped document. This proves old documents written before
// the migration deserialize to the correct Human/AIMessage with no backfill.
// ---------------------------------------------------------------------------

test("legacy {role,content,createdAt} documents deserialize to Human/AIMessage", () => {
  const legacyDocumentMessages: StoredChatMessage[] = [
    { role: "user", content: "what's my balance?", createdAt: new Date("2026-01-01T00:00:00.000Z") },
    { role: "assistant", content: "Your balance is 1,000 ILS.", createdAt: new Date("2026-01-01T00:00:01.000Z") }
  ];

  const loaded = trimConversationMessages(fromStored(legacyDocumentMessages));

  assert.equal(loaded.length, 2);
  assert.equal(loaded[0].getType(), "human");
  assert.equal(loaded[1].getType(), "ai");
  assert.equal(String(loaded[0].content), "what's my balance?");
  assert.equal(String(loaded[1].content), "Your balance is 1,000 ILS.");
});

test("legacy documents longer than the window trim to the most recent twenty", () => {
  const legacyDocumentMessages: StoredChatMessage[] = Array.from(
    { length: 25 },
    (_, index) => ({
      role: index % 2 === 0 ? "user" : "assistant",
      content: `legacy-${index}`,
      createdAt: new Date()
    })
  );

  const loaded = trimConversationMessages(fromStored(legacyDocumentMessages));

  assert.equal(loaded.length, 20);
  // Index 5 survives trimming first; odd index => assistant => AIMessage.
  assert.equal(String(loaded[0].content), "legacy-5");
  assert.equal(loaded[0].getType(), "ai");
});

// ---------------------------------------------------------------------------
// Prompt byte-identity (R2 / no prompt drift)
//
// Pre-migration the graph passed `state.messages` (the legacy stored `{ role,
// content, createdAt }` shape) into the LLM prompt builders. Post-migration it
// passes `toProviderMessages(state.messages)` (a `{ role, content }`
// projection of BaseMessage[]). These tests assert each builder emits a
// byte-identical prompt for both representations, including assistant-email
// masking, so classification/extraction/resolution behavior cannot drift.
// ---------------------------------------------------------------------------

// The legacy representation: what the old graph fed the builders (with createdAt).
const legacyMessages: StoredChatMessage[] = [
  { role: "user", content: "show my recent transfers", createdAt: new Date("2020-01-01T00:00:00.000Z") },
  { role: "assistant", content: "You last sent 50 ILS to alex@example.com.", createdAt: new Date("2020-01-01T00:00:01.000Z") },
  { role: "user", content: "send him 75 again", createdAt: new Date("2020-01-01T00:00:02.000Z") }
];

// The migrated representation: BaseMessage[] projected through toProviderMessages.
const migratedMessages = toProviderMessages([
  new HumanMessage("show my recent transfers"),
  new AIMessage("You last sent 50 ILS to alex@example.com."),
  new HumanMessage("send him 75 again")
]);

test("classifier prompt is byte-identical for legacy vs migrated messages", () => {
  const memory = createEmptyCounterpartyMemory();
  const legacyPrompt = buildClassifierPrompt({
    userMessage: "send him 75 again",
    messages: legacyMessages,
    counterpartyMemory: memory
  });
  const migratedPrompt = buildClassifierPrompt({
    userMessage: "send him 75 again",
    messages: migratedMessages,
    counterpartyMemory: memory
  });

  assert.equal(migratedPrompt, legacyPrompt);
  // Assistant email is masked in both (R3 masking preserved).
  assert.ok(migratedPrompt.includes("a***@example.com"));
  assert.ok(!migratedPrompt.includes("alex@example.com"));
});

test("transfer-draft prompt is byte-identical for legacy vs migrated messages", () => {
  const memory = createEmptyCounterpartyMemory();
  const legacyPrompt = buildTransferDraftPrompt({
    userMessage: "send him 75 again",
    messages: legacyMessages,
    counterpartyMemory: memory
  });
  const migratedPrompt = buildTransferDraftPrompt({
    userMessage: "send him 75 again",
    messages: migratedMessages,
    counterpartyMemory: memory
  });

  assert.equal(migratedPrompt, legacyPrompt);
});

test("reference-resolver prompt is byte-identical for legacy vs migrated messages", () => {
  const memory = createEmptyCounterpartyMemory();
  const legacyPrompt = buildReferenceResolverPrompt({
    userMessage: "send him 75 again",
    intent: "transfer_prepare",
    messages: legacyMessages,
    memory
  });
  const migratedPrompt = buildReferenceResolverPrompt({
    userMessage: "send him 75 again",
    intent: "transfer_prepare",
    messages: migratedMessages,
    memory
  });

  assert.equal(migratedPrompt, legacyPrompt);
});
