// Generated by OrchestKit Claude Plugin
// Created: 2026-06-14

/**
 * Single dispatch point between the v1 (deterministic-first) and v2 (LLM-first)
 * assistant graphs, selected by `config.ai.graphVersion`
 * (env `VIRLY_AI_GRAPH_VERSION`, default `v1`).
 *
 * Both graphs honour the identical `(RunAssistantInput, RunAssistantOptions) =>
 * RunAssistantResult` contract, so the HTTP routes and the conformance harness
 * call `runAssistant` and stay agnostic to which implementation serves the turn.
 */
import { config } from "../config.js";
import { runAssistantGraph } from "./graph.js";
import type {
  RunAssistantInput,
  RunAssistantOptions,
  RunAssistantResult
} from "./state.js";
import { runAssistantGraphV2 } from "./v2/graph.js";

export function runAssistant(
  input: RunAssistantInput,
  options: RunAssistantOptions = {}
): Promise<RunAssistantResult> {
  if (config.ai.graphVersion === "v2") {
    return runAssistantGraphV2(input, options);
  }
  return runAssistantGraph(input, options);
}
