// Generated by OrchestKit Claude Plugin
// Created: 2026-06-19

import assert from "node:assert/strict";
import test from "node:test";
import { User } from "./models/User.js";
import { AppError } from "./utils/app-error.js";
import { accountService } from "./services/account.service.js";

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

type MockUser = {
  _id: string;
  id: string;
  email: string;
  passwordHash: string;
  verificationTokenHash: string | null;
  phone: string;
  isVerified: boolean;
  balance: number;
  role: string;
};

function createMockUser(id: string, email: string): MockUser {
  return {
    _id: id,
    id,
    email,
    passwordHash: "super-secret-hash",
    verificationTokenHash: "secret-token-hash",
    phone: "+972500000000",
    isVerified: true,
    balance: 500,
    role: "user"
  };
}

function patchModel<T extends object, K extends keyof T>(
  model: T,
  key: K,
  value: T[K],
  t: test.TestContext
) {
  const original = model[key];
  model[key] = value;
  t.after(() => {
    model[key] = original;
  });
}

// Simulates Mongoose's .select() chaining by filtering out the specified fields
// from a document. Fields prefixed with "-" are excluded.
// The returned object is also a thenable so it can be awaited directly
// (for callers that don't chain .select()).
function buildSelectChain(doc: MockUser | null) {
  const chain = {
    then(
      resolve: (value: MockUser | null) => void,
      reject: (reason: unknown) => void
    ) {
      return Promise.resolve(doc).then(resolve, reject);
    },
    select(projection: string) {
      if (!doc) return Promise.resolve(null);
      const excluded = projection
        .split(/\s+/)
        .filter((f) => f.startsWith("-"))
        .map((f) => f.slice(1));
      const filtered = Object.fromEntries(
        Object.entries(doc).filter(([k]) => !excluded.includes(k))
      );
      return Promise.resolve(filtered as MockUser);
    }
  };
  return chain;
}

function patchFindById(t: test.TestContext, users: MockUser[]) {
  const byId = new Map(users.map((u) => [u._id, u]));
  patchModel(
    User,
    "findById",
    ((id: unknown) => {
      const doc = byId.get(String(id)) ?? null;
      return buildSelectChain(doc);
    }) as unknown as typeof User.findById,
    t
  );
}

function patchFindOne(t: test.TestContext, users: MockUser[]) {
  const byEmail = new Map(users.map((u) => [u.email, u]));
  patchModel(
    User,
    "findOne",
    (async (filter: { email?: string }) =>
      filter.email ? (byEmail.get(filter.email) ?? null) : null) as unknown as typeof User.findOne,
    t
  );
}

function patchCreate(t: test.TestContext, created: MockUser) {
  patchModel(
    User,
    "create",
    (async (_doc: unknown) => created) as unknown as typeof User.create,
    t
  );
}

// ---------------------------------------------------------------------------
// Tests
// ---------------------------------------------------------------------------

const userId = "507f1f77bcf86cd799439011";

test("getById returns user with secrets stripped from default projection", async (t) => {
  const mockUser = createMockUser(userId, "alice@example.com");
  patchFindById(t, [mockUser]);

  const user = await accountService.getById(userId);

  // Safe fields present
  assert.equal((user as unknown as Record<string, unknown>).id, userId);
  assert.equal((user as unknown as Record<string, unknown>).email, "alice@example.com");

  // Secret fields absent
  assert.equal((user as unknown as Record<string, unknown>).passwordHash, undefined);
  assert.equal((user as unknown as Record<string, unknown>).verificationTokenHash, undefined);
});

test("getById throws AppError(404) when user does not exist", async (t) => {
  patchFindById(t, []); // empty — findById returns null for any id

  await assert.rejects(
    () => accountService.getById(userId),
    (err: unknown) => {
      assert.ok(err instanceof AppError, "Expected AppError");
      assert.equal((err as AppError).status, 404);
      return true;
    }
  );
});

test("findById returns full document or null without throwing", async (t) => {
  const mockUser = createMockUser(userId, "alice@example.com");
  patchFindById(t, [mockUser]);

  const found = await accountService.findById(userId);
  assert.ok(found !== null);

  const missing = await accountService.findById("000000000000000000000000");
  assert.equal(missing, null);
});

test("findByEmail normalizes email to lowercase and finds user", async (t) => {
  const mockUser = createMockUser(userId, "alice@example.com");
  patchFindOne(t, [mockUser]);

  // Pass mixed-case + extra whitespace — service must normalize before querying
  const found = await accountService.findByEmail("  Alice@Example.COM  ");
  assert.ok(found !== null);
  assert.equal((found as unknown as Record<string, unknown>).email, "alice@example.com");
});

test("findByEmail returns null when email is not registered", async (t) => {
  patchFindOne(t, []);

  const result = await accountService.findByEmail("nobody@example.com");
  assert.equal(result, null);
});

test("findByIdOrEmail resolves a 24-hex ObjectId to a user", async (t) => {
  const mockUser = createMockUser(userId, "alice@example.com");
  patchFindById(t, [mockUser]);
  // findOne returns null — result must come from the findById branch only
  patchFindOne(t, []);

  const found = await accountService.findByIdOrEmail(userId);
  assert.ok(found !== null);
  assert.equal((found as unknown as Record<string, unknown>).id, userId);
});

test("findByIdOrEmail returns null when ObjectId is not found", async (t) => {
  patchFindById(t, []); // valid 24-hex id but not in the store
  patchFindOne(t, []);

  const result = await accountService.findByIdOrEmail(userId);
  assert.equal(result, null);
});

test("findByIdOrEmail resolves an email string to a user", async (t) => {
  const mockUser = createMockUser(userId, "alice@example.com");
  patchFindById(t, []);
  patchFindOne(t, [mockUser]);

  const found = await accountService.findByIdOrEmail("alice@example.com");
  assert.ok(found !== null);
  assert.equal((found as unknown as Record<string, unknown>).email, "alice@example.com");
});

test("findByIdOrEmail returns null for an invalid identifier", async (t) => {
  patchFindById(t, []);
  patchFindOne(t, []);

  // Not a 24-hex id, not a valid email
  const result = await accountService.findByIdOrEmail("not-a-valid-anything");
  assert.equal(result, null);
});

test("create inserts and returns a new user document", async (t) => {
  const created = createMockUser(userId, "new@example.com");
  patchCreate(t, created);

  const result = await accountService.create({
    email: "new@example.com",
    passwordHash: "hashed",
    phone: "+972500000001",
    balance: 0
  });

  assert.equal((result as unknown as Record<string, unknown>).email, "new@example.com");
});
