// Generated by OrchestKit Claude Plugin
// Created: 2026-06-21

import assert from "node:assert/strict";
import test from "node:test";
import { createMongoRepositories } from "./repositories/mongo/index.js";
import { setRepositories, type AiPendingTransferRecord } from "./repositories/index.js";
import { getResumablePendingForUser } from "./services/aiPendingTransfer.service.js";

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

const pendingTransferId = "507f1f77bcf86cd799439011";
const userId = "507f1f77bcf86cd799439022";

function baseRecord(overrides: Partial<AiPendingTransferRecord> = {}): AiPendingTransferRecord {
  return {
    id: pendingTransferId,
    userId,
    conversationId: "conv-abc",
    assistantId: "oshri",
    recipientEmail: "alice@example.com",
    version: 1,
    currency: "ILS",
    recipientFirstName: null,
    recipientLastName: null,
    amount: 100,
    reason: null,
    status: "pending",
    supersededById: null,
    supersedesId: null,
    idempotencyResults: {},
    expiresAt: new Date("2026-01-01T00:10:00.000Z"),
    createdAt: new Date("2026-01-01T00:00:00.000Z"),
    updatedAt: new Date("2026-01-01T00:00:00.000Z"),
    ...overrides
  };
}

/**
 * Installs a repository set whose aiPendingTransfers.findById is stubbed, then
 * restores the real Mongo repositories afterwards. Captures the id passed in.
 */
function stubFindById(
  t: test.TestContext,
  doc: AiPendingTransferRecord | null
): { capturedId: string | null } {
  const capture: { capturedId: string | null } = { capturedId: null };
  const repos = createMongoRepositories();
  repos.aiPendingTransfers = {
    ...repos.aiPendingTransfers,
    async findById(id: string) {
      capture.capturedId = id;
      return doc;
    }
  };
  setRepositories(repos);
  t.after(() => {
    setRepositories(createMongoRepositories());
  });
  return capture;
}

// ---------------------------------------------------------------------------
// getResumablePendingForUser (non-transaction path, routes through the repo)
// ---------------------------------------------------------------------------

test("getResumablePendingForUser queries the repo by pendingTransferId", async (t) => {
  const capture = stubFindById(t, baseRecord());

  await getResumablePendingForUser(pendingTransferId, userId);

  assert.equal(capture.capturedId, pendingTransferId, "must look up by pendingTransferId");
});

test("getResumablePendingForUser returns the conversationId from the record", async (t) => {
  stubFindById(t, baseRecord({ conversationId: "conv-abc" }));

  const result = await getResumablePendingForUser(pendingTransferId, userId);

  assert.ok(result !== null, "expected a result");
  assert.equal(result.conversationId, "conv-abc");
});

test("getResumablePendingForUser returns null when the record is missing", async (t) => {
  stubFindById(t, null);

  const result = await getResumablePendingForUser(pendingTransferId, userId);

  assert.equal(result, null);
});

test("getResumablePendingForUser returns null when the record belongs to another user", async (t) => {
  // Preserves the original `{ _id, userId }` ownership scoping.
  stubFindById(t, baseRecord({ userId: "507f1f77bcf86cd799439099" }));

  const result = await getResumablePendingForUser(pendingTransferId, userId);

  assert.equal(result, null, "must not resume a foreign user's pending transfer");
});
