// Generated by OrchestKit Claude Plugin
// Created: 2026-06-19

import assert from "node:assert/strict";
import test from "node:test";
import bcrypt from "bcryptjs";
import { User } from "./models/User.js";
import { PersonalDetails } from "./models/PersonalDetails.js";
import { AppError } from "./utils/app-error.js";
import { createVerificationToken } from "./utils/auth.js";
import { hashToken, verificationTokenExpiry } from "./utils/token.js";
import { config } from "./config.js";
import { authService } from "./services/auth.service.js";

// ---------------------------------------------------------------------------
// Mock user document
//
// These tests exercise authService against patched Mongoose statics (no live
// MongoDB), mirroring account.service.test.ts. A mock user is a plain object
// with a `save` spy so the service's persistence calls are observable.
// ---------------------------------------------------------------------------

type MockUser = {
  _id: string;
  id: string;
  email: string;
  passwordHash: string;
  phone: string;
  isVerified: boolean;
  balance: number;
  role: string;
  personalDetails: unknown;
  verificationTokenHash: string | null;
  verificationTokenExpiresAt: Date | null;
  createdAt: Date;
  saveCalls: number;
  save: () => Promise<void>;
};

function createMockUser(overrides: Partial<MockUser> = {}): MockUser {
  const user: MockUser = {
    _id: "507f1f77bcf86cd799439011",
    id: "507f1f77bcf86cd799439011",
    email: "alice@example.com",
    passwordHash: "placeholder-hash",
    phone: "+972500000000",
    isVerified: true,
    balance: 500,
    role: "user",
    personalDetails: { _id: "507f191e810c19729de860ea" },
    verificationTokenHash: null,
    verificationTokenExpiresAt: null,
    createdAt: new Date("2026-01-15T10:00:00.000Z"),
    saveCalls: 0,
    save: async () => {
      user.saveCalls += 1;
    },
    ...overrides
  };
  return user;
}

function patchModel<T extends object, K extends keyof T>(
  model: T,
  key: K,
  value: T[K],
  t: test.TestContext
) {
  const original = model[key];
  model[key] = value;
  t.after(() => {
    model[key] = original;
  });
}

function patchFindOne(t: test.TestContext, users: MockUser[]) {
  const byEmail = new Map(users.map((u) => [u.email, u]));
  patchModel(
    User,
    "findOne",
    (async (filter: { email?: string }) =>
      filter.email ? (byEmail.get(filter.email) ?? null) : null) as unknown as typeof User.findOne,
    t
  );
}

function patchFindById(t: test.TestContext, users: MockUser[]) {
  const byId = new Map(users.map((u) => [u._id, u]));
  patchModel(
    User,
    "findById",
    (async (id: unknown) => byId.get(String(id)) ?? null) as unknown as typeof User.findById,
    t
  );
}

function patchCreate(t: test.TestContext, onCreate: (doc: Record<string, unknown>) => MockUser) {
  patchModel(
    User,
    "create",
    (async (doc: Record<string, unknown>) => onCreate(doc)) as unknown as typeof User.create,
    t
  );
}

// personalDetailsService.ensureForUser hits PersonalDetails.findOneAndUpdate
// (upsert). Returning a doc avoids a real MongoDB round-trip so register
// stays focused on auth behavior.
function patchPersonalDetails(t: test.TestContext) {
  patchModel(
    PersonalDetails,
    "findOneAndUpdate",
    (async () => ({ _id: "507f191e810c19729de860ea", id: "507f191e810c19729de860ea", status: "not_provided" })) as unknown as typeof PersonalDetails.findOneAndUpdate,
    t
  );
}

// Observe WHETHER a verification email was triggered (the enumeration-safety
// guarantee) without real network calls or monkey-patching read-only ESM
// bindings. sendVerificationEmail logs "Verification link for ..." via
// console.log ONLY when no Resend sender is configured, so we force that
// fallback path by blanking config.email.resendApiKey for the test, then
// capture the log. config is a mutable exported object, restored in t.after.
function captureVerificationLogs(t: test.TestContext) {
  const originalKey = config.email.resendApiKey;
  config.email.resendApiKey = undefined;
  t.after(() => {
    config.email.resendApiKey = originalKey;
  });

  const links: string[] = [];
  const originalLog = console.log;
  console.log = (...args: unknown[]) => {
    const first = args[0];
    if (typeof first === "string" && first.startsWith("Verification link for")) {
      links.push(first);
    }
  };
  t.after(() => {
    console.log = originalLog;
  });
  return links;
}

// ---------------------------------------------------------------------------
// register
// ---------------------------------------------------------------------------

test("register: new email creates a user, returns a token, and emails a link", async (t) => {
  patchFindOne(t, []); // no existing user
  let createdInput: Record<string, unknown> | null = null;
  let created: MockUser | null = null;
  patchCreate(t, (doc) => {
    createdInput = doc;
    created = createMockUser({
      email: String(doc.email),
      passwordHash: String(doc.passwordHash),
      phone: String(doc.phone),
      balance: Number(doc.balance),
      isVerified: false
    });
    return created;
  });
  patchPersonalDetails(t);
  const links = captureVerificationLogs(t);

  const result = await authService.register({
    email: "New@Example.com",
    password: "supersecret",
    phone: "+972500000001"
  });

  // Email normalized + starting balance 0 + password hashed (not stored raw).
  assert.ok(createdInput);
  assert.equal((createdInput as Record<string, unknown>).email, "new@example.com");
  assert.equal((createdInput as Record<string, unknown>).balance, 0);
  assert.notEqual((createdInput as Record<string, unknown>).passwordHash, "supersecret");
  assert.ok(
    await bcrypt.compare(
      "supersecret",
      String((createdInput as Record<string, unknown>).passwordHash)
    ),
    "stored hash must verify against the raw password"
  );

  // Returns the created user + a verification token, and the token is persisted
  // as a HASH (never stored in cleartext).
  assert.equal(result.user, created);
  assert.ok(result.verificationToken.length > 0);
  assert.ok(created);
  assert.equal(
    (created as MockUser).verificationTokenHash,
    hashToken(result.verificationToken)
  );
  assert.equal((created as MockUser).saveCalls > 0, true);

  // A verification email was triggered.
  assert.equal(links.length, 1);
});

test("register: duplicate email throws AppError(409)", async (t) => {
  patchFindOne(t, [createMockUser({ email: "taken@example.com" })]);
  const links = captureVerificationLogs(t);

  await assert.rejects(
    () =>
      authService.register({
        email: "Taken@Example.com",
        password: "supersecret",
        phone: "+972500000001"
      }),
    (err: unknown) => {
      assert.ok(err instanceof AppError);
      assert.equal((err as AppError).status, 409);
      return true;
    }
  );

  // No email for an already-registered address.
  assert.equal(links.length, 0);
});

// ---------------------------------------------------------------------------
// login
// ---------------------------------------------------------------------------

test("login: correct password on a verified account returns the user", async (t) => {
  const passwordHash = await bcrypt.hash("correct horse", 10);
  const user = createMockUser({ email: "alice@example.com", passwordHash, isVerified: true });
  patchFindOne(t, [user]);

  const result = await authService.login({
    email: "Alice@Example.com",
    password: "correct horse"
  });

  assert.equal(result, user);
});

test("login: correct password on an UNVERIFIED account throws AppError(403)", async (t) => {
  const passwordHash = await bcrypt.hash("correct horse", 10);
  const user = createMockUser({ passwordHash, isVerified: false });
  patchFindOne(t, [user]);

  await assert.rejects(
    () => authService.login({ email: "alice@example.com", password: "correct horse" }),
    (err: unknown) => {
      assert.ok(err instanceof AppError);
      assert.equal((err as AppError).status, 403);
      return true;
    }
  );
});

test("login: wrong password throws AppError(401) with the generic message", async (t) => {
  const passwordHash = await bcrypt.hash("correct horse", 10);
  const user = createMockUser({ passwordHash, isVerified: true });
  patchFindOne(t, [user]);

  await assert.rejects(
    () => authService.login({ email: "alice@example.com", password: "wrong" }),
    (err: unknown) => {
      assert.ok(err instanceof AppError);
      assert.equal((err as AppError).status, 401);
      assert.equal((err as AppError).message, "Invalid email or password.");
      return true;
    }
  );
});

test("login: unknown email throws AppError(401) with the SAME message (no enumeration)", async (t) => {
  patchFindOne(t, []); // no such user

  await assert.rejects(
    () => authService.login({ email: "ghost@example.com", password: "whatever" }),
    (err: unknown) => {
      assert.ok(err instanceof AppError);
      assert.equal((err as AppError).status, 401);
      assert.equal((err as AppError).message, "Invalid email or password.");
      return true;
    }
  );
});

// ---------------------------------------------------------------------------
// verifyEmail
// ---------------------------------------------------------------------------

test("verifyEmail: valid unexpired matching token flips an unverified account", async (t) => {
  const token = createVerificationToken("507f1f77bcf86cd799439011");
  const user = createMockUser({
    isVerified: false,
    verificationTokenHash: hashToken(token),
    verificationTokenExpiresAt: verificationTokenExpiry()
  });
  patchFindById(t, [user]);

  const result = await authService.verifyEmail(token);

  assert.equal(result.alreadyVerified, false);
  assert.equal(result.user, user);
  assert.equal(user.isVerified, true);
  assert.equal(user.verificationTokenHash, null);
  assert.equal(user.verificationTokenExpiresAt, null);
  assert.equal(user.saveCalls > 0, true);
});

test("verifyEmail: already-verified account short-circuits without state change", async (t) => {
  const token = createVerificationToken("507f1f77bcf86cd799439011");
  const user = createMockUser({
    isVerified: true,
    verificationTokenHash: "stale-hash",
    verificationTokenExpiresAt: verificationTokenExpiry()
  });
  patchFindById(t, [user]);

  const result = await authService.verifyEmail(token);

  assert.equal(result.alreadyVerified, true);
  assert.equal(result.user, user);
  // No state mutation, no save.
  assert.equal(user.isVerified, true);
  assert.equal(user.verificationTokenHash, "stale-hash");
  assert.equal(user.saveCalls, 0);
});

test("verifyEmail: expired stored token throws AppError(400)", async (t) => {
  const token = createVerificationToken("507f1f77bcf86cd799439011");
  const user = createMockUser({
    isVerified: false,
    verificationTokenHash: hashToken(token),
    verificationTokenExpiresAt: new Date(Date.now() - 1000) // already expired
  });
  patchFindById(t, [user]);

  await assert.rejects(
    () => authService.verifyEmail(token),
    (err: unknown) => {
      assert.ok(err instanceof AppError);
      assert.equal((err as AppError).status, 400);
      return true;
    }
  );
  // State untouched on rejection.
  assert.equal(user.isVerified, false);
  assert.equal(user.saveCalls, 0);
});

test("verifyEmail: token hash mismatch throws AppError(400)", async (t) => {
  const token = createVerificationToken("507f1f77bcf86cd799439011");
  const user = createMockUser({
    isVerified: false,
    verificationTokenHash: hashToken("a-different-token"),
    verificationTokenExpiresAt: verificationTokenExpiry()
  });
  patchFindById(t, [user]);

  await assert.rejects(
    () => authService.verifyEmail(token),
    (err: unknown) => {
      assert.ok(err instanceof AppError);
      assert.equal((err as AppError).status, 400);
      return true;
    }
  );
  assert.equal(user.isVerified, false);
  assert.equal(user.saveCalls, 0);
});

test("verifyEmail: structurally invalid JWT throws AppError(400)", async (t) => {
  patchFindById(t, []);

  await assert.rejects(
    () => authService.verifyEmail("not-a-real-jwt"),
    (err: unknown) => {
      assert.ok(err instanceof AppError);
      assert.equal((err as AppError).status, 400);
      return true;
    }
  );
});

// ---------------------------------------------------------------------------
// resendVerification (enumeration-safe)
// ---------------------------------------------------------------------------

test("resendVerification: unverified existing user re-sends a link", async (t) => {
  const user = createMockUser({ email: "alice@example.com", isVerified: false });
  patchFindOne(t, [user]);
  const links = captureVerificationLogs(t);

  await authService.resendVerification("Alice@Example.com");

  assert.equal(links.length, 1);
  // A fresh token hash was persisted.
  assert.ok(user.verificationTokenHash);
  assert.equal(user.saveCalls > 0, true);
});

test("resendVerification: already-verified user sends nothing and does not throw", async (t) => {
  const user = createMockUser({ email: "alice@example.com", isVerified: true });
  patchFindOne(t, [user]);
  const links = captureVerificationLogs(t);

  await authService.resendVerification("alice@example.com");

  assert.equal(links.length, 0);
  assert.equal(user.saveCalls, 0);
});

test("resendVerification: absent user sends nothing and does not throw", async (t) => {
  patchFindOne(t, []);
  const links = captureVerificationLogs(t);

  await authService.resendVerification("ghost@example.com");

  assert.equal(links.length, 0);
});
