// Generated by OrchestKit Claude Plugin
// Created: 2026-06-21

import assert from "node:assert/strict";
import test from "node:test";
import { PersonalDetails } from "./models/PersonalDetails.js";
import { AppError } from "./utils/app-error.js";
import { personalDetailsService } from "./services/personalDetails.service.js";
import { setRepositories } from "./repositories/index.js";
import { createMongoRepositories } from "./repositories/mongo/index.js";
import type { Repositories, UserRecord } from "./repositories/types.js";

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

function patchModel<T extends object, K extends keyof T>(
  model: T,
  key: K,
  value: T[K],
  t: test.TestContext
) {
  const original = model[key];
  model[key] = value;
  t.after(() => {
    model[key] = original;
  });
}

type MockPersonalDetails = {
  _id: string;
  id: string;
  userId: string;
  status: string;
  firstName: string | null;
  lastName: string | null;
  dateOfBirth: Date | null;
  address: Record<string, string | null>;
  lastSkippedAt: Date | null;
  createdAt: Date;
  updatedAt: Date;
  saveCalls: number;
  save: () => Promise<void>;
};

function createMockDetails(overrides: Partial<MockPersonalDetails> = {}): MockPersonalDetails {
  const doc: MockPersonalDetails = {
    _id: "507f191e810c19729de860ea",
    id: "507f191e810c19729de860ea",
    userId: "507f1f77bcf86cd799439011",
    status: "not_provided",
    firstName: null,
    lastName: null,
    dateOfBirth: null,
    address: {},
    lastSkippedAt: null,
    createdAt: new Date("2026-01-01T00:00:00.000Z"),
    updatedAt: new Date("2026-01-01T00:00:00.000Z"),
    saveCalls: 0,
    save: async () => {
      doc.saveCalls += 1;
    },
    ...overrides
  };
  return doc;
}

function createUserRecord(overrides: Partial<UserRecord> = {}): UserRecord {
  return {
    id: "507f1f77bcf86cd799439011",
    email: "alice@example.com",
    passwordHash: "placeholder-hash",
    phone: "+972500000000",
    isVerified: true,
    balance: 0,
    role: "user",
    personalDetails: null,
    verificationTokenHash: null,
    verificationTokenExpiresAt: null,
    createdAt: new Date("2026-01-01T00:00:00.000Z"),
    updatedAt: new Date("2026-01-01T00:00:00.000Z"),
    ...overrides
  };
}

// ensureForUser now back-fills the User->PersonalDetails FK via the repository
// (getRepositories().users.setPersonalDetails) instead of user.save(). This
// stub captures those calls so the tests can assert on the back-fill.
function withSetPersonalDetailsSpy(t: test.TestContext) {
  const calls: Array<{ id: string; personalDetailsId: string }> = [];
  const base = createMongoRepositories();
  setRepositories({
    ...base,
    users: {
      ...base.users,
      setPersonalDetails: async (id: string, personalDetailsId: string) => {
        calls.push({ id, personalDetailsId });
      }
    } as Repositories["users"]
  });
  t.after(() => {
    setRepositories(base);
  });
  return calls;
}

// ---------------------------------------------------------------------------
// ensureForUser
// ---------------------------------------------------------------------------

test("ensureForUser: uses findOneAndUpdate upsert — does not call findOne or create", async (t) => {
  const details = createMockDetails({ status: "not_provided" });
  const user = createUserRecord({ personalDetails: null });
  withSetPersonalDetailsSpy(t);

  let findOneAndUpdateCalled = false;
  let findOneCalled = false;

  patchModel(
    PersonalDetails,
    "findOneAndUpdate",
    (async () => {
      findOneAndUpdateCalled = true;
      return details;
    }) as unknown as typeof PersonalDetails.findOneAndUpdate,
    t
  );

  patchModel(
    PersonalDetails,
    "findOne",
    (async () => {
      findOneCalled = true;
      return details;
    }) as unknown as typeof PersonalDetails.findOne,
    t
  );

  const result = await personalDetailsService.ensureForUser(user);

  assert.equal(result, details);
  assert.equal(findOneAndUpdateCalled, true, "must use findOneAndUpdate for upsert");
  assert.equal(findOneCalled, false, "must NOT fall back to findOne");
});

test("ensureForUser: back-fills the FK via setPersonalDetails when personalDetails is null", async (t) => {
  const details = createMockDetails();
  const user = createUserRecord({ personalDetails: null });
  const calls = withSetPersonalDetailsSpy(t);

  patchModel(
    PersonalDetails,
    "findOneAndUpdate",
    (async () => details) as unknown as typeof PersonalDetails.findOneAndUpdate,
    t
  );

  await personalDetailsService.ensureForUser(user);

  assert.equal(calls.length, 1, "should back-fill the FK once when personalDetails was null");
  assert.equal(calls[0]?.id, user.id);
  assert.equal(calls[0]?.personalDetailsId, String(details._id), "should set the returned doc._id");
});

test("ensureForUser: does NOT back-fill when user.personalDetails is already set", async (t) => {
  const details = createMockDetails();
  const user = createUserRecord({ personalDetails: "507f191e810c19729de860ea" });
  const calls = withSetPersonalDetailsSpy(t);

  patchModel(
    PersonalDetails,
    "findOneAndUpdate",
    (async () => details) as unknown as typeof PersonalDetails.findOneAndUpdate,
    t
  );

  await personalDetailsService.ensureForUser(user);

  assert.equal(calls.length, 0, "must NOT back-fill the FK when personalDetails was already set");
});

test("ensureForUser: idempotent — a record that already has the FK is not back-filled again", async (t) => {
  const details = createMockDetails();
  const calls = withSetPersonalDetailsSpy(t);

  patchModel(
    PersonalDetails,
    "findOneAndUpdate",
    (async () => details) as unknown as typeof PersonalDetails.findOneAndUpdate,
    t
  );

  // First call: no FK yet -> one back-fill.
  await personalDetailsService.ensureForUser(createUserRecord({ personalDetails: null }));
  assert.equal(calls.length, 1);

  // Second call: a record whose FK is already populated (as it would be after
  // a reload following the first call) -> no further back-fill.
  await personalDetailsService.ensureForUser(
    createUserRecord({ personalDetails: String(details._id) })
  );
  assert.equal(calls.length, 1, "second call must NOT back-fill again");
});

// ---------------------------------------------------------------------------
// getForUser
// ---------------------------------------------------------------------------

test("getForUser: returns the doc when found", async (t) => {
  const details = createMockDetails({ userId: "507f1f77bcf86cd799439011" });

  patchModel(
    PersonalDetails,
    "findOne",
    (async () => details) as unknown as typeof PersonalDetails.findOne,
    t
  );

  const result = await personalDetailsService.getForUser("507f1f77bcf86cd799439011");
  assert.equal(result, details);
});

test("getForUser: returns null when not found", async (t) => {
  patchModel(
    PersonalDetails,
    "findOne",
    (async () => null) as unknown as typeof PersonalDetails.findOne,
    t
  );

  const result = await personalDetailsService.getForUser("507f1f77bcf86cd799439011");
  assert.equal(result, null);
});

// ---------------------------------------------------------------------------
// getDisplayName
// ---------------------------------------------------------------------------

test("getDisplayName: returns firstName/lastName only when status is 'provided'", async (t) => {
  const details = createMockDetails({
    status: "provided",
    firstName: "Alice",
    lastName: "Goldberg"
  });

  patchModel(
    PersonalDetails,
    "findOne",
    (async () => details) as unknown as typeof PersonalDetails.findOne,
    t
  );

  const result = await personalDetailsService.getDisplayName("507f1f77bcf86cd799439011");
  assert.deepEqual(result, { firstName: "Alice", lastName: "Goldberg" });
});

test("getDisplayName: returns null when status is 'not_provided'", async (t) => {
  const details = createMockDetails({ status: "not_provided", firstName: "Bob" });

  patchModel(
    PersonalDetails,
    "findOne",
    (async () => details) as unknown as typeof PersonalDetails.findOne,
    t
  );

  const result = await personalDetailsService.getDisplayName("507f1f77bcf86cd799439011");
  assert.equal(result, null);
});

test("getDisplayName: returns null when no doc exists", async (t) => {
  patchModel(
    PersonalDetails,
    "findOne",
    (async () => null) as unknown as typeof PersonalDetails.findOne,
    t
  );

  const result = await personalDetailsService.getDisplayName("507f1f77bcf86cd799439011");
  assert.equal(result, null);
});

// ---------------------------------------------------------------------------
// update
// ---------------------------------------------------------------------------

test("update: sets status to 'provided' and persists all fields", async (t) => {
  const details = createMockDetails({ status: "not_provided" });

  patchModel(
    PersonalDetails,
    "findOneAndUpdate",
    (async (_filter: unknown, update: Record<string, unknown>, _opts: unknown) => {
      // simulate applying the update to our mock doc
      const set = (update as { $set?: Record<string, unknown> }).$set ?? {};
      Object.assign(details, set);
      details.saveCalls += 1;
      return details;
    }) as unknown as typeof PersonalDetails.findOneAndUpdate,
    t
  );

  const input = {
    firstName: "Carol",
    lastName: "Danvers",
    dateOfBirth: "1990-03-05",
    address: {
      country: "US",
      stateRegion: null,
      city: "New York",
      street: "5th Ave",
      addressLine2: null,
      postalCode: "10001"
    }
  };

  const result = await personalDetailsService.update("507f1f77bcf86cd799439011", input);

  assert.equal(result.status, "provided");
  assert.equal(result.firstName, "Carol");
  assert.equal(result.lastName, "Danvers");
  assert.ok(result.dateOfBirth instanceof Date || typeof result.dateOfBirth === "string" || result.dateOfBirth !== undefined);
});

test("update: throws AppError(404) when doc does not exist", async (t) => {
  patchModel(
    PersonalDetails,
    "findOneAndUpdate",
    (async () => null) as unknown as typeof PersonalDetails.findOneAndUpdate,
    t
  );

  await assert.rejects(
    () =>
      personalDetailsService.update("507f1f77bcf86cd799439011", {
        firstName: "Carol",
        lastName: "Danvers",
        dateOfBirth: "1990-03-05",
        address: {
          country: "US",
          stateRegion: null,
          city: "New York",
          street: "5th Ave",
          addressLine2: null,
          postalCode: "10001"
        }
      }),
    (err: unknown) => {
      assert.ok(err instanceof AppError);
      assert.equal((err as AppError).status, 404);
      return true;
    }
  );
});

// ---------------------------------------------------------------------------
// markSkipped
// ---------------------------------------------------------------------------

test("markSkipped: sets lastSkippedAt and persists", async (t) => {
  const details = createMockDetails({ lastSkippedAt: null });
  const before = Date.now();

  patchModel(
    PersonalDetails,
    "findOneAndUpdate",
    (async (_filter: unknown, update: Record<string, unknown>, _opts: unknown) => {
      const set = (update as { $set?: Record<string, unknown> }).$set ?? {};
      Object.assign(details, set);
      return details;
    }) as unknown as typeof PersonalDetails.findOneAndUpdate,
    t
  );

  const result = await personalDetailsService.markSkipped("507f1f77bcf86cd799439011");

  assert.ok(result.lastSkippedAt instanceof Date || result.lastSkippedAt !== null);
  if (result.lastSkippedAt instanceof Date) {
    assert.ok(result.lastSkippedAt.getTime() >= before);
  }
});

test("markSkipped: throws AppError(404) when doc does not exist", async (t) => {
  patchModel(
    PersonalDetails,
    "findOneAndUpdate",
    (async () => null) as unknown as typeof PersonalDetails.findOneAndUpdate,
    t
  );

  await assert.rejects(
    () => personalDetailsService.markSkipped("507f1f77bcf86cd799439011"),
    (err: unknown) => {
      assert.ok(err instanceof AppError);
      assert.equal((err as AppError).status, 404);
      return true;
    }
  );
});
