/**
 * capture-screenshots.ts — Storybook screenshot capture (NOT RUN YET).
 *
 * ┌─────────────────────────────────────────────────────────────────────────┐
 * │ STATUS: scaffold only. Storybook is being built separately. Do NOT wire  │
 * │ this into CI or run it until Storybook is available. Until then the docs │
 * │ use the placeholder PNGs generated by `make-placeholders.sh`.            │
 * └─────────────────────────────────────────────────────────────────────────┘
 *
 * Method A (Storybook): iterate stories, screenshot each, and write to
 *   images/<name>--<state>.png
 * which is exactly the path the Markdown already references — so enabling real
 * capture is a drop-in replacement with zero Markdown edits.
 *
 * Enable later:
 *   1. Start Storybook (e.g. `npm --prefix client run storybook`, default :6006).
 *   2. Create one story per (component, state) using the name `<Component>/<State>`
 *      (see images/TODO.md — the "Story name" column is pre-filled to match).
 *   3. Install Playwright in the docs toolchain: `npm i -D playwright`.
 *   4. Run: `STORYBOOK_URL=http://localhost:6006 npx tsx docs/frontend/capture/capture-screenshots.ts`
 *
 * The `targets` array is the single source of truth for what gets captured.
 * Keep it in sync with `_inventory.md` / `images/TODO.md` (ideally generate it
 * from the same list).
 */

// NOTE: `playwright` is intentionally not a dependency yet. This import will
// only resolve once Playwright is installed (step 3 above).
// import { chromium, type Browser, type Page } from "playwright";

export type Viewport = { width: number; height: number };

export const DESKTOP_VIEWPORT: Viewport = { width: 1440, height: 900 };
export const MOBILE_VIEWPORT: Viewport = { width: 390, height: 844 };

export type CaptureTarget = {
  /** Component name; becomes the `<name>` half of `<name>--<state>.png`. */
  name: string;
  /** Storybook story id/name, by convention `<Component>/<State>`. */
  story: string;
  /** State label; becomes the `<state>` half of `<name>--<state>.png`. */
  state: string;
  /** Optional CSS selector to clip the screenshot to a single element. */
  selector?: string;
  /** Capture viewport (defaults to 1440x900). */
  viewport?: Viewport;
  /** Set true to also produce a 390x844 mobile pass (responsive components). */
  mobile?: boolean;
};

/**
 * Seed targets. This is a representative subset — extend it to cover every row
 * in images/TODO.md (or generate it from that table). Filenames produced here
 * must match the Markdown references, e.g. images/TransferCheque--error.png.
 */
export const targets: CaptureTarget[] = [
  { name: "TransferCheque", story: "TransferCheque/Default", state: "default", mobile: true },
  { name: "TransferCheque", story: "TransferCheque/Error", state: "error" },
  { name: "TransferCheque", story: "TransferCheque/Review", state: "review" },
  { name: "TransferCheque", story: "TransferCheque/Success", state: "success" },
  { name: "TransferPage", story: "TransferPage/Default", state: "default", mobile: true },
  { name: "FloatingChatWidget", story: "FloatingChatWidget/Default", state: "default", mobile: true },
  { name: "FloatingChatWidget", story: "FloatingChatWidget/Loading", state: "loading" },
  { name: "FloatingChatWidget", story: "FloatingChatWidget/Success", state: "success" },
  { name: "AssistantBlocks", story: "AssistantBlocks/Default", state: "default" },
  { name: "TransactionDetailsDialog", story: "TransactionDetailsDialog/Default", state: "default" },
];

const OUT_DIR = new URL("../images/", import.meta.url).pathname;
const STORYBOOK_URL = process.env.STORYBOOK_URL ?? "http://localhost:6006";

/** Storybook iframe URL for a given story id (Method A). */
function storyUrl(story: string): string {
  const id = story.toLowerCase().replace(/\//g, "-").replace(/\s+/g, "-");
  return `${STORYBOOK_URL}/iframe.html?id=${encodeURIComponent(id)}&viewMode=story`;
}

function outFile(name: string, state: string, mobile = false): string {
  const suffix = mobile ? `${state}--mobile` : state;
  return `${OUT_DIR}${name}--${suffix}.png`;
}

/**
 * Real capture loop — commented out until Playwright + Storybook are available.
 * Uncomment, install playwright, and remove the `notRunYet()` guard to enable.
 */
async function run(): Promise<void> {
  notRunYet();

  /*
  const browser: Browser = await chromium.launch();
  try {
    for (const target of targets) {
      const passes: Viewport[] = [target.viewport ?? DESKTOP_VIEWPORT];
      if (target.mobile) passes.push(MOBILE_VIEWPORT);

      for (const viewport of passes) {
        const isMobile = viewport.width === MOBILE_VIEWPORT.width;
        const page: Page = await browser.newPage({ viewport });
        await page.goto(storyUrl(target.story), { waitUntil: "networkidle" });

        const clip = target.selector ? await page.$(target.selector) : null;
        const path = outFile(target.name, target.state, isMobile);

        if (clip) {
          await clip.screenshot({ path });
        } else {
          await page.screenshot({ path, fullPage: false });
        }

        console.log(`captured ${path}`);
        await page.close();
      }
    }
  } finally {
    await browser.close();
  }
  */
}

function notRunYet(): never {
  throw new Error(
    "capture-screenshots.ts is a scaffold and is not enabled yet. " +
      "Storybook is in progress; until it is available, the docs use placeholder " +
      "PNGs from make-placeholders.sh. See the header for enable steps.",
  );
}

// Only execute when run directly (e.g. `npx tsx capture-screenshots.ts`).
// Guarded so importing the `targets`/helpers never triggers a capture.
if (import.meta.url === `file://${process.argv[1]}`) {
  run().catch((error) => {
    console.error(error);
    process.exit(1);
  });
}
