// Generated by OrchestKit Claude Plugin
// Created: 2026-06-24

// src/repositories/postgres/errors.ts
import { DuplicateKeyError } from "../types.js";
export function mapPgError(e: unknown, key: string): never {
  if (e && typeof e === "object" && (e as { code?: string }).code === "23505") {
    throw new DuplicateKeyError(key);
  }
  throw e;
}
