// Generated by OrchestKit Claude Plugin
// Created: 2026-06-24

// src/repositories/postgres/id.test.ts
import assert from "node:assert/strict";
import test from "node:test";
import { newObjectId, isObjectIdHex } from "./id.js";

test("newObjectId returns a fresh 24-hex string", () => {
  const a = newObjectId();
  assert.match(a, /^[0-9a-f]{24}$/);
  assert.notEqual(a, newObjectId());
});

test("isObjectIdHex accepts 24-hex and rejects junk", () => {
  assert.equal(isObjectIdHex("507f1f77bcf86cd799439011"), true);
  assert.equal(isObjectIdHex("nope"), false);
});
