// Generated by OrchestKit Claude Plugin
// Created: 2026-06-24

// src/repositories/postgres/id.ts
import mongoose from "mongoose";
export function newObjectId(): string { return new mongoose.Types.ObjectId().toString(); }
export function isObjectIdHex(id: string): boolean { return /^[0-9a-fA-F]{24}$/.test(id); }
