// Generated by OrchestKit Claude Plugin
// Created: 2026-06-24

import type { Repositories } from "../types.js";
import { runInTransaction } from "./transaction.js";
import type { PgDatabase } from "../../db/postgres.js";
import { postgresUserRepository } from "./user.repository.js";

// Stub — Task 5+ fill in the real per-entity repos.
export function createPostgresRepositories(_db?: PgDatabase): Repositories {
  return {
    users: postgresUserRepository,
    transactions: {} as Repositories["transactions"],
    personalDetails: {} as Repositories["personalDetails"],
    exchangeRates: {} as Repositories["exchangeRates"],
    aiConversations: {} as Repositories["aiConversations"],
    aiPendingTransfers: {} as Repositories["aiPendingTransfers"],
    aiAuditLogs: {} as Repositories["aiAuditLogs"],
    videoSessions: {} as Repositories["videoSessions"],
    videoAuditLogs: {} as Repositories["videoAuditLogs"],
    runInTransaction
  };
}
