// Generated by OrchestKit Claude Plugin
// Created: 2026-06-14

/**
 * Graph v2 — LLM-first agent loop entrypoint.
 *
 * `runAssistantGraphV2` is the v2 counterpart of v1's `runAssistantGraph`: same
 * `(RunAssistantInput, RunAssistantOptions) => RunAssistantResult` contract, so
 * it is a drop-in behind the `VIRLY_AI_GRAPH_VERSION` flag and re-targets the V2
 * conformance suite without any change to callers.
 *
 * Phase 0 ships this as a graceful stub; Phases 1–4 replace the body with the
 * real `prepare → agent ⇄ tools → finalize → persist` loop. (Phase 5 — transfer
 * execution via interrupt/resume — stays stubbed.)
 */
import { DEFAULT_ASSISTANT_ID } from "../assistants.js";
import { assistantResponseFormatVersion } from "../responseBlocks.js";
import type {
  RunAssistantInput,
  RunAssistantOptions,
  RunAssistantResult
} from "../state.js";

const V2_NOT_READY_MESSAGE =
  "The v2 assistant is not available yet. Please try again shortly.";

export async function runAssistantGraphV2(
  input: RunAssistantInput,
  _options: RunAssistantOptions = {}
): Promise<RunAssistantResult> {
  return {
    message: V2_NOT_READY_MESSAGE,
    responseMessage: V2_NOT_READY_MESSAGE,
    responseFormatVersion: assistantResponseFormatVersion,
    conversationId: input.conversationId,
    assistantId: input.assistantId ?? DEFAULT_ASSISTANT_ID,
    intent: "unsupported",
    toolCalls: [],
    toolResults: []
  };
}
