// Generated by OrchestKit Claude Plugin
// Created: 2026-06-14

/**
 * Human-in-the-loop transfer path (design §8 / Phase 5).
 *
 * The resumable graph is the same read-only loop plus a money branch:
 *
 *   prepare → agent ⇄ tools → finalize → (card? transferGate : persist)
 *   transferGate --interrupt--> [Confirm → executeTransfer | Deny] → persist
 *
 * It is compiled WITH a checkpointer so `interrupt()` can pause on a prepared
 * card and `Command({ resume })` can continue later from the authenticated
 * confirmation endpoint. The conformance suite does NOT use this graph (it drives
 * the non-resumable per-turn entry); this is the production HITL path.
 */
import { AIMessage, HumanMessage } from "@langchain/core/messages";
import {
  END,
  MemorySaver,
  START,
  StateGraph,
  type BaseCheckpointSaver,
  type LangGraphRunnableConfig
} from "@langchain/langgraph";
import mongoose from "mongoose";

import { DEFAULT_ASSISTANT_ID } from "../assistants.js";
import { createEmptyCounterpartyMemory } from "../counterpartyMemory.js";
import { assistantResponseFormatVersion } from "../responseBlocks.js";
import { readOnlyToolExecutors } from "../tools/index.js";
import {
  modifyAiPendingTransfer,
  prepareAiPendingTransfer,
  respondToAiPendingTransfer
} from "../../services/aiPendingTransfer.service.js";
import type {
  RunAssistantInput,
  RunAssistantOptions,
  RunAssistantResult
} from "../state.js";

import { buildAgentNode } from "./agent.js";
import { createMongoCheckpointer } from "./memory/checkpointer.js";
import { createV2ChatModel, isV2ModelConfigured } from "./model.js";
import { executeTransferNode } from "./nodes/executeTransfer.js";
import { finalizeNode } from "./nodes/finalize.js";
import { persistNode } from "./nodes/persist.js";
import { prepareNode } from "./nodes/prepare.js";
import { transferGateNode, type TransferResumePayload } from "./nodes/transferGate.js";
import { V2AgentState, type V2AgentStateType } from "./state.js";
import type { V2Configurable, V2TurnOutcome } from "./toolContext.js";
import { createV2ToolNode } from "./tools/index.js";
import {
  buildKnownCounterparties,
  detectLocale,
  pendingFromConfirmation
} from "./turn.js";

const V2_TIMEZONE = "Asia/Jerusalem";

function routeAgent(state: V2AgentStateType): "tools" | "finalize" {
  const last = state.messages.at(-1);
  const toolCalls = last instanceof AIMessage ? last.tool_calls ?? [] : [];
  return toolCalls.length > 0 ? "tools" : "finalize";
}

/** After finalize, a prepared card pauses for human confirmation; else we're done. */
function routeAfterFinalize(state: V2AgentStateType): "transferGate" | "persist" {
  return state.confirmation ? "transferGate" : "persist";
}

export function buildResumableGraph(checkpointer: BaseCheckpointSaver) {
  const model = createV2ChatModel();
  return new StateGraph(V2AgentState)
    .addNode("prepare", prepareNode)
    .addNode("agent", buildAgentNode(model))
    .addNode("tools", createV2ToolNode())
    .addNode("finalize", finalizeNode)
    .addNode("transferGate", transferGateNode, { ends: ["executeTransfer", "persist"] })
    .addNode("executeTransfer", executeTransferNode)
    .addNode("persist", persistNode)
    .addEdge(START, "prepare")
    .addEdge("prepare", "agent")
    .addConditionalEdges("agent", routeAgent, { tools: "tools", finalize: "finalize" })
    .addEdge("tools", "agent")
    .addConditionalEdges("finalize", routeAfterFinalize, {
      transferGate: "transferGate",
      persist: "persist"
    })
    .addEdge("executeTransfer", "persist")
    .addEdge("persist", END)
    .compile({ checkpointer });
}

type ResumableGraph = ReturnType<typeof buildResumableGraph>;

let cachedResumableGraph: ResumableGraph | undefined;

/** The production resumable graph, checkpointed in MongoDB when connected. */
function getResumableGraph(): ResumableGraph {
  if (!cachedResumableGraph) {
    let checkpointer: BaseCheckpointSaver;
    try {
      checkpointer = createMongoCheckpointer(mongoose.connection.getClient());
    } catch {
      // No live Mongo connection (dev/degraded): fall back to in-memory.
      checkpointer = new MemorySaver();
    }
    cachedResumableGraph = buildResumableGraph(checkpointer);
  }
  return cachedResumableGraph;
}

function configurableFor(
  input: RunAssistantInput,
  options: RunAssistantOptions,
  turnOutcome: V2TurnOutcome,
  memoryKnownCounterparties: V2Configurable["knownCounterparties"],
  pendingConfirmation: V2Configurable["pendingConfirmation"]
): V2Configurable {
  return {
    userId: input.userId ?? "",
    conversationId: input.conversationId,
    assistantId: input.assistantId ?? DEFAULT_ASSISTANT_ID,
    message: input.message,
    now: new Date(),
    timezone: V2_TIMEZONE,
    locale: detectLocale(input.message),
    executors: options.tools ?? readOnlyToolExecutors,
    transferPreparationService:
      options.transferPreparationService ?? prepareAiPendingTransfer,
    transferModificationService:
      options.transferModificationService ?? modifyAiPendingTransfer,
    transferResponseService: respondToAiPendingTransfer,
    pendingConfirmation,
    turnOutcome,
    knownCounterparties: memoryKnownCounterparties
  };
}

function hasInterrupt(state: unknown): boolean {
  const interrupts = (state as { __interrupt__?: unknown[] }).__interrupt__;
  return Array.isArray(interrupts) && interrupts.length > 0;
}

/**
 * Production HITL turn: invokes the resumable graph by `thread_id = conversationId`.
 * A transfer turn pauses at `transferGate` (checkpointed) and returns the card;
 * read-only turns complete normally.
 */
export async function invokeV2Resumable(
  input: RunAssistantInput,
  options: RunAssistantOptions = {},
  graph: ResumableGraph = getResumableGraph()
): Promise<RunAssistantResult> {
  const assistantId = input.assistantId ?? DEFAULT_ASSISTANT_ID;
  const locale = detectLocale(input.message);
  if (!isV2ModelConfigured()) {
    const message =
      locale === "he"
        ? "מצטער, לא הצלחתי לעבד את הבקשה כרגע."
        : "Sorry, I couldn't process that just now.";
    return {
      message,
      responseMessage: message,
      responseFormatVersion: assistantResponseFormatVersion,
      conversationId: input.conversationId,
      assistantId,
      intent: "unsupported",
      toolCalls: [],
      toolResults: []
    };
  }

  const store = options.conversationStore;
  const loaded = store
    ? await store.load(input.userId ?? "", input.conversationId)
    : { messages: [], memory: createEmptyCounterpartyMemory() };
  const memory = loaded.memory ?? createEmptyCounterpartyMemory();

  const turnOutcome: V2TurnOutcome = { uiBlocks: [] };
  const configurable = configurableFor(
    input,
    options,
    turnOutcome,
    buildKnownCounterparties(memory),
    memory.pendingConfirmation ?? null
  );

  const out = (await graph.invoke(
    { messages: [new HumanMessage(input.message)] },
    { configurable: { ...configurable, thread_id: input.conversationId }, recursionLimit: 25 }
  )) as V2AgentStateType;

  const paused = hasInterrupt(out);
  const responseMessage =
    out.responseMessage?.trim() ||
    (turnOutcome.confirmation
      ? locale === "he"
        ? "הכנתי העברה לאישורך."
        : "I've prepared a transfer for your confirmation."
      : "");

  return {
    message: responseMessage,
    responseMessage,
    responseFormatVersion: assistantResponseFormatVersion,
    ...(turnOutcome.uiBlocks.length > 0 ? { responseBlocks: turnOutcome.uiBlocks } : {}),
    conversationId: input.conversationId,
    assistantId,
    intent: turnOutcome.confirmation ? "transfer_prepare" : "general_help",
    toolCalls: [],
    toolResults: [],
    ...(turnOutcome.clarification ? { clarification: turnOutcome.clarification } : {}),
    ...(paused && turnOutcome.confirmation ? { confirmation: turnOutcome.confirmation } : {}),
    ...(turnOutcome.supersededConfirmationId
      ? { supersededConfirmationId: turnOutcome.supersededConfirmationId }
      : {})
  };
}

/**
 * Resume a checkpointed transfer from the confirmation endpoint with the user's
 * Confirm/Deny. Returns the backend transfer-execution result (the same
 * `AiConfirmationResult` shape the v1 path returns).
 */
export async function resumeV2Confirmation(
  args: {
    userId: string;
    conversationId: string;
    payload: TransferResumePayload;
  },
  graph: ResumableGraph = getResumableGraph()
): Promise<unknown> {
  const { Command } = await import("@langchain/langgraph");
  const configurable: V2Configurable = {
    userId: args.userId,
    conversationId: args.conversationId,
    assistantId: DEFAULT_ASSISTANT_ID,
    message: "",
    now: new Date(),
    timezone: V2_TIMEZONE,
    locale: "en",
    executors: readOnlyToolExecutors,
    transferResponseService: respondToAiPendingTransfer,
    turnOutcome: { uiBlocks: [] },
    knownCounterparties: []
  };

  const out = (await graph.invoke(new Command({ resume: args.payload }), {
    configurable: { ...configurable, thread_id: args.conversationId }
  })) as V2AgentStateType;

  return out.transferResult;
}

/** Test seam: pending-card → memory mapping reused by the resumable persist. */
export { pendingFromConfirmation };
