// Generated by OrchestKit Claude Plugin
// Created: 2026-06-14

/**
 * The v2 agent model: a `ChatOpenAI` built from `config.ai` (design §9).
 *
 * Same OpenAI key/model the rest of the app uses, but used as a *tool-calling
 * agent* (not v1's structured-output extractors). Low temperature for stable
 * tool selection; a generous timeout because a turn may chain several tool hops.
 */
import { ChatOpenAI } from "@langchain/openai";

import { config } from "../../config.js";

export function isV2ModelConfigured(): boolean {
  return Boolean(config.ai.openAIApiKey.trim() && config.ai.model.trim());
}

export function createV2ChatModel(): ChatOpenAI {
  return new ChatOpenAI({
    apiKey: config.ai.openAIApiKey,
    model: config.ai.model,
    temperature: 0,
    maxRetries: 2,
    timeout: 60_000
  });
}
