// Generated by OrchestKit Claude Plugin
// Created: 2026-06-14

/**
 * Pure per-turn helpers for the v2 entry: locale detection, building the
 * known-counterparties prompt list from conversation memory, mapping a prepared
 * card into pending-confirmation memory, and deriving audit fields
 * (executed tools / intent) from the message thread + turn outcome.
 */
import type { BaseMessage } from "@langchain/core/messages";

import { aiToolCalls } from "./messages.js";

import type {
  AssistantIntent,
  AssistantToolName,
  CounterpartyMemory,
  PendingConfirmationMemory,
  TransferConfirmation
} from "../state.js";
import type { KnownCounterparty } from "./prompt.js";
import type { V2TurnOutcome } from "./toolContext.js";

const HEBREW = /[֐-׿]/;
const LATIN = /[A-Za-z]/;

export function detectLocale(
  message: string
): "he" | "en" | "mixed" | "unknown" {
  const hasHebrew = HEBREW.test(message);
  const hasLatin = LATIN.test(message);
  if (hasHebrew && hasLatin) return "mixed";
  if (hasHebrew) return "he";
  if (hasLatin) return "en";
  return "unknown";
}

function capitalize(value: string): string {
  return value ? value.charAt(0).toUpperCase() + value.slice(1) : value;
}

/** Build the "name/alias -> email" list injected into the system prompt. */
export function buildKnownCounterparties(
  memory: CounterpartyMemory
): KnownCounterparty[] {
  return memory.mentionedCounterparties.map((ref) => {
    const localpart = ref.email.split("@")[0] ?? ref.email;
    const label =
      ref.displayName ??
      (ref.userLabel && !ref.userLabel.includes("@")
        ? ref.userLabel
        : capitalize(localpart));
    const aliases = Array.from(
      new Set(
        [...(ref.aliases ?? []), localpart].filter(
          (alias) => alias && !alias.includes("@") && alias !== label
        )
      )
    );
    return { email: ref.email, label, aliases };
  });
}

/** Map a prepared confirmation card into pending-confirmation memory for next turn. */
export function pendingFromConfirmation(
  card: TransferConfirmation,
  turn: number
): PendingConfirmationMemory {
  return {
    confirmationId: card.id,
    type: "transfer",
    status: "pending",
    createdAt: new Date().toISOString(),
    expiresAt: card.expiresAt,
    recipientEmail: card.recipientEmail,
    recipientFirstName: card.recipientFirstName,
    recipientLastName: card.recipientLastName,
    amount: card.amount,
    currency: card.currency,
    reason: card.reason,
    turnCreated: turn,
    version: card.version
  };
}

const V2_TO_V1_READ_TOOL: Partial<Record<string, AssistantToolName>> = {
  getAccounts: "getUserAccounts",
  getBalance: "getAccountBalance",
  searchTransactions: "searchTransactions",
  getTransactionReceipt: "getTransactionReceipt",
  findCounterparty: "resolveCounterpartyCandidates",
  getCounterpartySummary: "getCounterpartySummary",
  getCounterpartyTransactions: "getTransactionsWithCounterparty",
  getTotals: "getTotalSentToCounterparty",
  getRecentSent: "getRecentSentCounterparties",
  getRecentReceived: "getRecentReceivedCounterparties",
  getLastSent: "getLastSentCounterparty",
  getVerifiedRecipients: "getVerifiedRecipients",
  getTransferLimits: "getTransferLimits",
  checkTransferEligibility: "getTransferEligibility",
  getTransferQuote: "getTransferQuote",
  getDailyTransferUsage: "getDailyTransferUsage",
  getPendingTransfers: "getPendingAiTransfers"
};

/** Every v2 tool name the model called this turn, in order. */
export function collectCalledToolNames(messages: BaseMessage[]): string[] {
  const names: string[] = [];
  for (const message of messages) {
    // aiToolCalls matches AIMessageChunk too (streaming-robust; see ./messages.ts).
    for (const call of aiToolCalls(message)) {
      names.push(call.name);
    }
  }
  return names;
}

/** Read-tool calls mapped to AssistantToolName for the audit log / result. */
export function mapReadToolNames(v2Names: string[]): AssistantToolName[] {
  const mapped: AssistantToolName[] = [];
  for (const name of v2Names) {
    const v1 = V2_TO_V1_READ_TOOL[name];
    if (v1) {
      mapped.push(v1);
    }
  }
  return mapped;
}

/** A coarse intent for the audit log (not asserted by conformance). */
export function deriveIntent(outcome: V2TurnOutcome): AssistantIntent {
  if (outcome.confirmation && outcome.supersededConfirmationId) {
    return "transfer_modify_pending";
  }
  if (outcome.confirmation) {
    return "transfer_prepare";
  }
  if (outcome.clarification) {
    return "transfer_prepare";
  }
  return "general_help";
}
